// <auto-generated />

#pragma warning disable 618, 612, 414, 168, CS1591, SA1129, SA1309, SA1312, SA1403, SA1649, CS8669

using MsgPack = global::MessagePack;

namespace MessagePack {
partial class GeneratedMessagePackResolver {
internal partial class TempProject {

	internal sealed class ItemFormatter<T> : MsgPack::Formatters.IMessagePackFormatter<global::TempProject.Item<T>>
	{

		public void Serialize(ref MsgPack::MessagePackWriter writer, global::TempProject.Item<T> value, MsgPack::MessagePackSerializerOptions options)
		{
			MsgPack::IFormatterResolver formatterResolver = options.Resolver;
			writer.WriteArrayHeader(1);
			MsgPack::FormatterResolverExtensions.GetFormatterWithVerify<string>(formatterResolver).Serialize(ref writer, value.Key, options);
		}

		public global::TempProject.Item<T> Deserialize(ref MsgPack::MessagePackReader reader, MsgPack::MessagePackSerializerOptions options)
		{
			if (reader.TryReadNil())
			{
				throw new global::System.InvalidOperationException("typecode is null, struct not supported");
			}

			options.Security.DepthStep(ref reader);
			MsgPack::IFormatterResolver formatterResolver = options.Resolver;
			var length = reader.ReadArrayHeader();
			var __Key__ = default(string);

			for (int i = 0; i < length; i++)
			{
				switch (i)
				{
					case 0:
						__Key__ = MsgPack::FormatterResolverExtensions.GetFormatterWithVerify<string>(formatterResolver).Deserialize(ref reader, options);
						break;
					default:
						reader.Skip();
						break;
				}
			}

			var ____result = new global::TempProject.Item<T>(__Key__);
			reader.Depth--;
			return ____result;
		}
	}
}
}
}
