using System.Collections.Immutable;

namespace MessagePack.SourceGenerator;

/// <summary>
/// Emits the single per-assembly factory over every generated formatter (object and
/// union) plus the module-initializer registration into SourceGeneratedFormatterFactory.
/// Non-generic types construct directly; generic types register their OPEN definition
/// and serve closed requests two ways: instantiations harvested from the serialized
/// member graph construct statically (the Native AOT route, which also skips Activator
/// on CoreCLR), and anything else closes the open formatter over the runtime type
/// arguments via MakeGenericType (declined on Native AOT, where ref struct buffer
/// arguments cannot be closed — the resolver's formatter-not-found surfaces instead of
/// a reflection crash).
/// </summary>
static class FactoryEmitter
{
    public static string EmitFactory(ImmutableArray<(ObjectModel? Object, UnionModel? Union)> models, ImmutableArray<AttributeFormatterTypeModel> attributeModels, ImmutableArray<SurrogateModel> surrogateModels)
    {
        // one surrogate per target: duplicates are a MsgPack018 error reported by the
        // generator's duplicate-site node, so first-by-name here just keeps the (already
        // failing) emission deterministic
        var orderedSurrogates = surrogateModels
            .GroupBy(static m => m.TargetTypeName, StringComparer.Ordinal)
            .Select(static group => group.OrderBy(static m => m.SurrogateTypeName, StringComparer.Ordinal).First())
            .OrderBy(static m => m.TargetTypeName, StringComparer.Ordinal)
            .ToArray();
        var ordered = models
            .Where(static pair => pair.Object is not null)
            .Select(static pair => pair.Object!)
            .OrderBy(static m => m.FullTypeName, StringComparer.Ordinal)
            .ToArray();
        var orderedUnions = models
            .Where(static pair => pair.Union is not null)
            .Select(static pair => pair.Union!)
            .OrderBy(static m => m.FullTypeName, StringComparer.Ordinal)
            .ToArray();
        var orderedAttributes = attributeModels
            .OrderBy(static m => m.FullTypeName, StringComparer.Ordinal)
            .ToArray();
        var anyGeneric = ordered.Any(static m => m.OpenFormatterTypeOf.Length > 0)
            || orderedUnions.Any(static m => m.OpenFormatterTypeOf.Length > 0);

        // harvested closed instantiations, joined against the open models that actually
        // exist (a suppressed or invalid definition never got a model — drop its harvest);
        // nested (AllowPrivate) formatters are skipped: their closed form lives inside the
        // user's type and the MakeGenericType fallback still serves them on CoreCLR.
        // The value is the open formatter reference: object and generic-union models alike.
        var genericByOpen = new Dictionary<string, string>(StringComparer.Ordinal);
        foreach (var model in ordered)
        {
            if (model.OpenFormatterTypeOf.Length > 0 && !model.EmitNested)
            {
                genericByOpen[model.OpenTypeOf] = model.FormatterReference;
            }
        }
        foreach (var model in orderedUnions)
        {
            if (model.OpenFormatterTypeOf.Length > 0)
            {
                genericByOpen[model.OpenTypeOf] = "global::MessagePack.Generated." + model.FormatterName;
            }
        }
        var harvestedInstantiations = ordered
            .SelectMany(static m => m.HarvestedGenerics)
            .GroupBy(static h => h.ClosedTypeName, StringComparer.Ordinal)
            .Select(static g => g.First())
            .Where(h => genericByOpen.ContainsKey(h.OpenTypeOf))
            .OrderBy(static h => h.ClosedTypeName, StringComparer.Ordinal)
            .ToArray();

        // enums, Nullable<T>, and BCL collection/wrapper closed forms (List<string>,
        // string[], ...) from the member graph: statically constructed and registered, so
        // the Native AOT chain (which omits the RequiresDynamicCode GenericFormatterFactory
        // tier) resolves them
        var harvestedBuiltIns = ordered.SelectMany(static m => m.HarvestedBuiltIns)
            .Concat(orderedUnions.SelectMany(static m => m.HarvestedBuiltIns))
            .GroupBy(static h => h.ClosedTypeName, StringComparer.Ordinal)
            .Select(static g => g.First())
            .OrderBy(static h => h.ClosedTypeName, StringComparer.Ordinal)
            .ToArray();

        var writer = CodeWriter.Rent();
        writer.Line("// <auto-generated/>");
        writer.Line("#nullable enable annotations");
        writer.Line("using SerializerFoundation;");
        writer.Line("using MessagePack;");
        writer.Line();
        var ns = writer.Block("namespace MessagePack.Generated");

        writer.Line("internal sealed class GeneratedMessagePackFormatterFactory : MessagePackFormatterFactory");
        var factory = writer.OpenScope();

        writer.Line("public static readonly GeneratedMessagePackFormatterFactory Instance = new GeneratedMessagePackFormatterFactory();");
        writer.Line();
        writer.Line("GeneratedMessagePackFormatterFactory()");
        using (writer.OpenScope())
        {
        }

        writer.Line();
        AppendGenericCreateFormatterSignature(writer);
        using (writer.OpenScope())
        {
            // type-level [MessagePackFormatter] first: on a type that ALSO has a generated
            // object formatter, the annotation wins (v3's AttributeFormatterResolver sat
            // before its source-generated tier; here the same precedence is compiled in).
            // The resolver initializes whatever this factory returns, so no Initialize here.
            foreach (var model in orderedAttributes)
            {
                if (model.Custom.FactoryNew is { } factoryNew)
                {
                    writer.Line("#if NET9_0_OR_GREATER");
                    writer.Line($"if (type == typeof({model.FullTypeName})) return {factoryNew}.CreateFormatter<TWriteBuffer, TReadBuffer>(type);");
                    writer.Line("#else");
                    writer.Line($"if (type == typeof({model.FullTypeName})) return {factoryNew}.CreateFormatter(typeof(TWriteBuffer), typeof(TReadBuffer), type);");
                    writer.Line("#endif");
                }
                else
                {
                    writer.Line($"if (type == typeof({model.FullTypeName})) return {model.Custom.FormatterNew};");
                }
            }
            // surrogate-declared targets (IMessagePackSurrogate implementations): before
            // the harvested constructions, so a surrogate target that is also reachable as
            // a collection-shaped member resolves through its surrogate deterministically
            foreach (var surrogate in orderedSurrogates)
            {
                writer.Line($"if (type == typeof({surrogate.TargetTypeName})) return new global::MessagePack.Formatters.SurrogateFormatter<TWriteBuffer, TReadBuffer, {surrogate.TargetTypeName}, {surrogate.SurrogateTypeName}>();");
            }
            foreach (var model in ordered)
            {
                if (model.OpenFormatterTypeOf.Length == 0)
                {
                    writer.Line($"if (type == typeof({model.FullTypeName})) return new {model.FormatterReference}<TWriteBuffer, TReadBuffer>();");
                }
            }
            foreach (var model in orderedUnions)
            {
                if (model.OpenFormatterTypeOf.Length == 0)
                {
                    writer.Line($"if (type == typeof({model.FullTypeName})) return new global::MessagePack.Generated.{model.FormatterName}<TWriteBuffer, TReadBuffer>();");
                }
            }
            foreach (var instantiation in harvestedInstantiations)
            {
                writer.Line($"if (type == typeof({instantiation.ClosedTypeName})) return new {genericByOpen[instantiation.OpenTypeOf]}<TWriteBuffer, TReadBuffer, {string.Join(", ", instantiation.TypeArguments)}>();");
            }
            foreach (var builtIn in harvestedBuiltIns)
            {
                writer.Line($"if (type == typeof({builtIn.ClosedTypeName})) return {builtIn.FormatterConstruction};");
            }
            foreach (var model in ordered)
            {
                if (model.OpenFormatterTypeOf.Length > 0)
                {
                    writer.Line($"if (type.IsGenericType && !type.IsGenericTypeDefinition && type.GetGenericTypeDefinition() == typeof({model.OpenTypeOf})) return CreateGenericFormatter(typeof({model.OpenFormatterTypeOf}), typeof(TWriteBuffer), typeof(TReadBuffer), type);");
                }
            }
            foreach (var model in orderedUnions)
            {
                if (model.OpenFormatterTypeOf.Length > 0)
                {
                    writer.Line($"if (type.IsGenericType && !type.IsGenericTypeDefinition && type.GetGenericTypeDefinition() == typeof({model.OpenTypeOf})) return CreateGenericFormatter(typeof({model.OpenFormatterTypeOf}), typeof(TWriteBuffer), typeof(TReadBuffer), type);");
                }
            }
            writer.Line("return null;");
        }

        if (anyGeneric)
        {
            writer.Line();
            writer.Line("#if NET5_0_OR_GREATER");
            writer.Line("[global::System.Diagnostics.CodeAnalysis.UnconditionalSuppressMessage(\"AOT\", \"IL3050\", Justification = \"guarded by RuntimeFeature.IsDynamicCodeSupported: Native AOT returns null (resolver not-found) instead of closing dynamically\")]");
            writer.Line("[global::System.Diagnostics.CodeAnalysis.UnconditionalSuppressMessage(\"Trimming\", \"IL2055\", Justification = \"the formatter definition and its type parameters are rooted by the typeof references at the call sites above\")]");
            writer.Line("[global::System.Diagnostics.CodeAnalysis.UnconditionalSuppressMessage(\"Trimming\", \"IL2067\", Justification = \"generated formatters always have a public parameterless constructor, rooted by the same typeof references\")]");
            writer.Line("#endif");
            writer.Line("static object? CreateGenericFormatter(global::System.Type formatterDefinition, global::System.Type writeBufferType, global::System.Type readBufferType, global::System.Type closedValueType)");
            using (writer.OpenScope())
            {
                writer.Line("// Native AOT cannot close a generic over the byref-like buffer types");
                writer.Line("// (MakeGenericType throws TypeLoadException for ref struct arguments);");
                writer.Line("// declining here surfaces the resolver's actionable formatter-not-found");
                writer.Line("// error instead of a reflection crash");
                using (writer.Block("if (!global::System.Runtime.CompilerServices.RuntimeFeature.IsDynamicCodeSupported)"))
                {
                    writer.Line("return null;");
                }
                writer.Line("var valueArguments = closedValueType.GetGenericArguments();");
                writer.Line("var arguments = new global::System.Type[valueArguments.Length + 2];");
                writer.Line("arguments[0] = writeBufferType;");
                writer.Line("arguments[1] = readBufferType;");
                writer.Line("valueArguments.CopyTo(arguments, 2);");
                writer.Line("return global::System.Activator.CreateInstance(formatterDefinition.MakeGenericType(arguments));");
            }
        }

        writer.Line();
        // the Type-based member (the base class's only abstract one): dispatch the
        // built-in buffer pairs into the generic method above
        BufferPairs.AppendCreateFormatterDispatch(writer);
        factory.Dispose();

        writer.Line();
        writer.Line("internal static class GeneratedMessagePackRegistration");
        using (writer.OpenScope())
        {
            writer.Line("// The default options resolve through SourceGeneratedFormatterFactory, so");
            writer.Line("// generated types work without manual registration; an explicit chain can");
            writer.Line("// still place GeneratedMessagePackFormatterFactory.Instance directly.");
            writer.Line("[global::System.Runtime.CompilerServices.ModuleInitializer]");
            writer.Line("internal static void Register()");
            using (writer.OpenScope())
            {
                foreach (var model in orderedAttributes)
                {
                    writer.Line($"SourceGeneratedFormatterFactory.Instance.Register(typeof({model.FullTypeName}), GeneratedMessagePackFormatterFactory.Instance);");
                }
                foreach (var surrogate in orderedSurrogates)
                {
                    writer.Line($"SourceGeneratedFormatterFactory.Instance.Register(typeof({surrogate.TargetTypeName}), GeneratedMessagePackFormatterFactory.Instance);");
                }
                foreach (var model in ordered)
                {
                    writer.Line($"SourceGeneratedFormatterFactory.Instance.Register(typeof({model.OpenTypeOf}), GeneratedMessagePackFormatterFactory.Instance);");
                }
                foreach (var model in orderedUnions)
                {
                    writer.Line($"SourceGeneratedFormatterFactory.Instance.Register(typeof({model.OpenTypeOf}), GeneratedMessagePackFormatterFactory.Instance);");
                }
                foreach (var builtIn in harvestedBuiltIns)
                {
                    writer.Line($"SourceGeneratedFormatterFactory.Instance.Register(typeof({builtIn.ClosedTypeName}), GeneratedMessagePackFormatterFactory.Instance);");
                }
            }
        }

        ns.Dispose();
        return writer.ToStringAndReturn();
    }

    static void AppendGenericCreateFormatterSignature(CodeWriter writer)
    {
        writer.Line("// one method, two signatures: net9+ overrides the base virtual (constraints");
        writer.Line("// inherited); downlevel has no base member, so the constraints are spelled out");
        writer.Line("#if NET9_0_OR_GREATER");
        writer.Line("public override object? CreateFormatter<TWriteBuffer, TReadBuffer>(global::System.Type type)");
        writer.Line("#else");
        writer.Line("public object? CreateFormatter<TWriteBuffer, TReadBuffer>(global::System.Type type)");
        writer.Indent();
        writer.Line("where TWriteBuffer : struct, IWriteBuffer");
        writer.Line("where TReadBuffer : struct, IReadBuffer");
        writer.Unindent();
        writer.Line("#endif");
    }

    /// <summary>
    /// Emits the generated half of a [MessagePackSerializable]-annotated partial factory
    /// class: the MessagePackFormatterFactory base, an Instance, static closed
    /// constructions for the class's harvested root closure, and a module-initializer
    /// registration of each closed type into SourceGeneratedFormatterFactory — so root-only
    /// shapes resolve through DefaultAot, while Instance stays composable in explicit chains.
    /// </summary>
    public static string EmitSerializableFactory(SerializableFactoryModel model, ImmutableArray<(ObjectModel? Object, UnionModel? Union)> models)
    {
        // the same open-model join EmitFactory performs: a harvested closed user generic is
        // constructible only when its open [MessagePackObject] definition produced a
        // non-nested model in this compilation
        var genericByOpen = new Dictionary<string, string>(StringComparer.Ordinal);
        foreach (var (obj, union) in models)
        {
            if (obj is { OpenFormatterTypeOf.Length: > 0, EmitNested: false })
            {
                genericByOpen[obj.OpenTypeOf] = obj.FormatterReference;
            }
            if (union is { OpenFormatterTypeOf.Length: > 0 })
            {
                genericByOpen[union.OpenTypeOf] = "global::MessagePack.Generated." + union.FormatterName;
            }
        }
        var instantiations = model.HarvestedGenerics
            .Where(h => genericByOpen.ContainsKey(h.OpenTypeOf))
            .OrderBy(static h => h.ClosedTypeName, StringComparer.Ordinal)
            .ToArray();

        var writer = CodeWriter.Rent();
        writer.Line("// <auto-generated/>");
        writer.Line("#nullable enable annotations");
        writer.Line("using SerializerFoundation;");
        writer.Line("using MessagePack;");
        writer.Line();

        var declarations = model.Declarations.ToArray();
        var scopes = new List<CodeWriter.BlockScope>(declarations.Length);
        for (int i = 0; i < declarations.Length - 1; i++)
        {
            scopes.Add(writer.Block(declarations[i]));
        }
        // the class's own declaration carries the base here, so the user half may omit it
        scopes.Add(writer.Block(declarations[declarations.Length - 1] + " : global::MessagePack.MessagePackFormatterFactory"));

        writer.Line($"public static readonly {model.FullTypeName} Instance = new {model.FullTypeName}();");
        writer.Line();
        AppendGenericCreateFormatterSignature(writer);
        using (writer.OpenScope())
        {
            foreach (var instantiation in instantiations)
            {
                writer.Line($"if (type == typeof({instantiation.ClosedTypeName})) return new {genericByOpen[instantiation.OpenTypeOf]}<TWriteBuffer, TReadBuffer, {string.Join(", ", instantiation.TypeArguments)}>();");
            }
            foreach (var builtIn in model.HarvestedBuiltIns)
            {
                writer.Line($"if (type == typeof({builtIn.ClosedTypeName})) return {builtIn.FormatterConstruction};");
            }
            writer.Line("return null;");
        }

        writer.Line();
        BufferPairs.AppendCreateFormatterDispatch(writer);

        var registrations = instantiations.Select(static h => h.ClosedTypeName)
            .Concat(model.HarvestedBuiltIns.Select(static h => h.ClosedTypeName))
            .OrderBy(static name => name, StringComparer.Ordinal)
            .ToArray();
        if (registrations.Length > 0)
        {
            writer.Line();
            writer.Line("[global::System.Runtime.CompilerServices.ModuleInitializer]");
            writer.Line("internal static void RegisterMessagePackRoots()");
            using (writer.OpenScope())
            {
                foreach (var registration in registrations)
                {
                    writer.Line($"global::MessagePack.SourceGeneratedFormatterFactory.Instance.Register(typeof({registration}), Instance);");
                }
            }
        }

        for (int i = scopes.Count - 1; i >= 0; i--)
        {
            scopes[i].Dispose();
        }
        return writer.ToStringAndReturn();
    }
}
