using System.Text;

namespace MessagePack.SourceGenerator;

/// <summary>
/// Emits one formatter class per [MessagePackObject] type. Output shape follows the
/// measured house style:
///   Serialize   - direct-writable members (and headers/keys) are batched into shared
///                 reservations: one GetReference over the summed worst-case sizes, a
///                 register-resident offset, one Advance per run (PocoPerValueVsBatchBenchmark: -11..16%
///                 vs per-value calls). A member without a direct writer flushes the run
///                 and dispatches through its formatter field — which is where String and
///                 DateTime now live (see DirectKind: their wire form is chain-configurable).
///                 The formatter call reads value.X exactly once, as its argument, so a
///                 property returning a different string per call can no longer diverge the
///                 reservation from the write. String KEYS stay fused as pre-encoded
///                 header+utf8 blobs via UnsafeWriteRaw (compile-time constants; measured
///                 no defusion penalty on BenchPerson).
///   Deserialize - per-value loop+switch (int keys) or utf8 in-place key match (string
///                 keys); unknown keys/extra array slots are skipped for version
///                 tolerance. Measured equal to straight-line reads (the decode chain
///                 dominates), and it handles count mismatches naturally.
///                 Types with a matched constructor or init-only members read into locals
///                 and construct at the end (`new T(args) { inits }`); a caller-supplied
///                 class instance still takes the populate path, mirroring
///                 ReflectionObjectFormatter's Arguments-mode split.
///   Nested      - formatters resolved once in Initialize into interface fields
///                 (NestedFormatterDispatchBenchmark: per-call resolution is strictly worse).
///   AllowPrivate- the formatter is emitted as a nested class inside the (partial) target
///                 type, which is what grants private-member access without reflection.
/// </summary>
static class ObjectEmitter
{
    public static string HintName(ObjectModel model) => model.EmitNested
        ? ObjectParser.Sanitize(model.FullTypeName) + "Formatter"
        : model.FormatterName;

    // wide seenMembers tier: stackalloc up to this many members, heap array beyond
    const int StackallocSeenMembersLimit = 256;

    static string ValueType(ObjectModel model) => model.IsValueType ? model.FullTypeName : model.FullTypeName + "?";

    static string FormatterTypeParameters(ObjectModel model) => model.TypeParameterList.Length == 0
        ? "TWriteBuffer, TReadBuffer"
        : "TWriteBuffer, TReadBuffer, " + model.TypeParameterList;

    public static string EmitFormatter(ObjectModel model)
    {
        var writer = CodeWriter.Rent();
        var valueType = ValueType(model);

        writer.Line("// <auto-generated/>");
        writer.Line("#nullable enable annotations");
        writer.Line("using SerializerFoundation;");
        writer.Line("using System.Buffers.Binary;");
        writer.Line("using System.Runtime.CompilerServices;");
        writer.Line("using MessagePack;");
        writer.Line("using static MessagePack.MessagePackPrimitives;");
        writer.Line();

        var containers = new List<CodeWriter.BlockScope>();
        if (model.EmitNested)
        {
            foreach (var declaration in model.NestedDeclarations)
            {
                containers.Add(writer.Block(declaration));
            }
        }
        else
        {
            containers.Add(writer.Block("namespace MessagePack.Generated"));
        }

        writer.Line($"internal sealed class {model.FormatterName}<{FormatterTypeParameters(model)}> : IMessagePackFormatter<TWriteBuffer, TReadBuffer, {valueType}>");
        writer.Indent();
        EmitBufferConstraints(writer);
        foreach (var clause in model.WhereClauses)
        {
            writer.Line(clause);
        }
        writer.Unindent();
        using (writer.OpenScope())
        {
            foreach (var member in model.Members)
            {
                if (member.Direct == DirectKind.None)
                {
                    writer.Line($"IMessagePackFormatter<TWriteBuffer, TReadBuffer, {member.TypeName}> f{member.Name} = null!;");
                }
            }
            // validation flags snapshot the RESOLVER's configuration: the flags are part
            // of the formatter graph's identity, so strict and lenient resolvers coexist
            if (AnyRequired(model))
            {
                writer.Line("bool validateRequired;");
            }
            if (AnyNullCheck(model))
            {
                writer.Line("bool validateNull;");
            }

            writer.Line();
            writer.Line("public void Initialize(MessagePackFormatterResolver resolver)");
            using (writer.OpenScope())
            {
                foreach (var member in model.Members)
                {
                    if (member.CustomFormatter is { FactoryNew: { } factoryNew, TypeOfExpr: { } typeOfExpr })
                    {
                        // mirror the resolver's factory invocation shape: generic overload
                        // on the modern surface, the Type-based compat overload downlevel
                        var fieldType = $"IMessagePackFormatter<TWriteBuffer, TReadBuffer, {member.TypeName}>";
                        var mismatch = $"throw new global::System.InvalidOperationException(\"[MessagePackFormatter] factory did not create a formatter for '{typeOfExpr}' ({model.FullTypeName}.{member.Name}).\")";
                        writer.Line("#if NET9_0_OR_GREATER");
                        writer.Line($"f{member.Name} = {factoryNew}.CreateFormatter<TWriteBuffer, TReadBuffer>(typeof({typeOfExpr})) as {fieldType} ?? {mismatch};");
                        writer.Line("#else");
                        writer.Line($"f{member.Name} = {factoryNew}.CreateFormatter(typeof(TWriteBuffer), typeof(TReadBuffer), typeof({typeOfExpr})) as {fieldType} ?? {mismatch};");
                        writer.Line("#endif");
                        writer.Line($"f{member.Name}.Initialize(resolver);");
                    }
                    else if (member.CustomFormatter is { FormatterNew: { } formatterNew })
                    {
                        // the cast erases nullability-annotation differences between the
                        // formatter's T and the member's declared type
                        writer.Line($"f{member.Name} = (IMessagePackFormatter<TWriteBuffer, TReadBuffer, {member.TypeName}>){formatterNew};");
                        writer.Line($"f{member.Name}.Initialize(resolver);");
                    }
                    else if (member.Direct == DirectKind.None)
                    {
                        writer.Line($"f{member.Name} = resolver.GetFormatter<TWriteBuffer, TReadBuffer, {member.TypeName}>();");
                    }
                }
                if (AnyRequired(model))
                {
                    writer.Line("validateRequired = resolver.ValidateRequiredMembers;");
                }
                if (AnyNullCheck(model))
                {
                    writer.Line("validateNull = resolver.ValidateNullableAnnotations;");
                }
            }

            writer.Line();
            EmitSerialize(writer, model, valueType);
            writer.Line();
            EmitDeserialize(writer, model, valueType);
            if (AnyRequired(model))
            {
                writer.Line();
                EmitRequiredThrowHelper(writer, model);
            }
            if (AnyNullCheck(model))
            {
                writer.Line();
                EmitNullThrowHelper(writer, model);
            }
        }

        for (int i = containers.Count - 1; i >= 0; i--)
        {
            containers[i].Dispose();
        }
        return writer.ToStringAndReturn();
    }

    internal static void EmitBufferConstraints(CodeWriter writer)
    {
        writer.Line("where TWriteBuffer : struct, IWriteBuffer");
        writer.Line("#if NET9_0_OR_GREATER");
        writer.Line(", allows ref struct");
        writer.Line("#endif");
        writer.Line("where TReadBuffer : struct, IReadBuffer");
        writer.Line("#if NET9_0_OR_GREATER");
        writer.Line(", allows ref struct");
        writer.Line("#endif");
    }

    static void EmitSerialize(CodeWriter writer, ObjectModel model, string valueType)
    {
        writer.Line($"public void Serialize(ref TWriteBuffer buffer, ref SerializeState state, {valueType} value)");
        using var body = writer.OpenScope();
        if (!model.IsValueType)
        {
            using (writer.Block("if (value == null)"))
            {
                writer.Line("buffer.WriteNil();");
                writer.Line("return;");
            }
            writer.Line();
        }
        if (model.AllowCircularReferences)
        {
            // register-before-write: a cycle back into an in-progress ancestor takes the
            // back-reference branch naturally
            using (writer.Block("if (state.TrackCircularReference(value, out var circularReferenceId))"))
            {
                writer.Line("buffer.WriteCircularReferenceBackReference(circularReferenceId);");
                writer.Line("return;");
            }
            writer.Line();
        }
        EmitCallback(writer, model.OnBeforeSerialize, model, "value", "OnBeforeSerialize");
        writer.Line("state.Enter();");
        writer.Line();
        if (model.UnknownMembersName is { } unknownName)
        {
            // read once: the header count and the replay below must see the same packet
            writer.Line($"var unknownMembers = value.{unknownName};");
        }

        // batched write runs: consecutive direct-writable items share one reservation
        var sizes = new List<string>();
        var writes = new List<string>();
        var comments = new List<string?>();

        void Direct(string sizeExpression, string writeCall, string? comment = null)
        {
            sizes.Add(sizeExpression);
            writes.Add(writeCall);
            comments.Add(comment);
        }

        static string Trailing(string? comment) => comment is null ? "" : $" // {comment}";

        void Flush()
        {
            if (writes.Count == 0)
            {
                return;
            }
            if (writes.Count == 1)
            {
                // a lone item needs no offset chain
                writer.Line($"buffer.Advance({writes[0].Replace("{DEST}", $"ref buffer.GetReference({sizes[0]})")});{Trailing(comments[0])}");
            }
            else
            {
                using (writer.OpenScope())
                {
                    writer.Line($"ref var d = ref buffer.GetReference({string.Join(" + ", sizes)});");
                    writer.Line("var w = 0;");
                    for (int i = 0; i < writes.Count; i++)
                    {
                        writer.Line($"w += {writes[i].Replace("{DEST}", "ref Unsafe.Add(ref d, w)")};{Trailing(comments[i])}");
                    }
                    writer.Line("buffer.Advance(w);");
                }
            }
            sizes.Clear();
            writes.Clear();
            comments.Clear();
        }

        if (model.AllowCircularReferences)
        {
            // the envelope joins the same reservation run as the member header that follows
            Direct("1", "UnsafeWriteFixArrayHeader({DEST}, 2)", "circular-reference envelope [id, body]");
            Direct("MaxUInt32Length", "UnsafeWriteUInt32({DEST}, circularReferenceId)");
        }

        if (!model.IsStringKey)
        {
            var count = model.MaxIntKey + 1;
            var hasKeyHoles = model.Members.Length < count;
            if (model.UnknownMembersName is null)
            {
                Direct(
                    count <= 15 ? "1" : "MaxArrayHeaderLength",
                    count <= 15 ? $"UnsafeWriteFixArrayHeader({{DEST}}, {count})" : $"UnsafeWriteArrayHeader({{DEST}}, {count})");
            }
            else
            {
                // captured trailing elements extend the array: the count is dynamic, but
                // the reservation stays a constant worst case and the header simply joins
                // the same fused run with a runtime count
                writer.Line($"var arrayCount = SourceGeneratorHelper.GetUnknownArrayCount(unknownMembers, {count});");
                if (hasKeyHoles)
                {
                    // captured entries ascend by index, so one cursor serves every hole
                    // and hands the trailing replay its remaining entries
                    writer.Line("var unknownReplayedCount = 0;");
                }
                Direct("MaxArrayHeaderLength", "UnsafeWriteArrayHeader({DEST}, arrayCount)");
            }

            var byKey = model.Members.AsArray().ToDictionary(static m => m.IntKey);
            for (int key = 0; key <= model.MaxIntKey; key++)
            {
                if (byKey.TryGetValue(key, out var member))
                {
                    EmitValueWrite(writer, member, (size, call) => Direct(size, call), Flush);
                }
                else if (model.UnknownMembersName is null)
                {
                    Direct("1", "UnsafeWriteNil({DEST})", $"key {key}: no member"); // key hole
                }
                else
                {
                    // a hole may replay a captured entry of unbounded size (a wider
                    // writer's value at this retired key), so it leaves the fused
                    // constant run and goes through the cursor: entry or nil padding
                    Flush();
                    writer.Line($"buffer.WriteUnknownIntKeyedHole(unknownMembers, ref unknownReplayedCount, {key});");
                }
            }
        }
        else
        {
            var count = model.Members.Length;
            if (model.UnknownMembersName is null)
            {
                Direct(
                    count <= 15 ? "1" : "MaxMapHeaderLength",
                    count <= 15 ? $"UnsafeWriteFixMapHeader({{DEST}}, {count})" : $"UnsafeWriteMapHeader({{DEST}}, {count})");
            }
            else
            {
                writer.Line($"var mapCount = unknownMembers is null ? {count} : {count} + unknownMembers.Count;");
                Direct("MaxMapHeaderLength", "UnsafeWriteMapHeader({DEST}, mapCount)");
            }

            foreach (var member in model.Members)
            {
                // key = compile-time constant: header + utf8 pre-encoded into one blob,
                // written as a raw copy (the byte[]-to-ReadOnlySpan argument conversion
                // compiles to RVA static data, no allocation). Both the blob and its size
                // are constants, so the reservation can never diverge from the write.
                var keyBlob = EncodeStringKeyBlob(member.StringKey);
                Direct(
                    keyBlob.Length.ToString(),
                    $"UnsafeWriteRaw({{DEST}}, new byte[] {{ {string.Join(", ", keyBlob.Select(static b => $"0x{b:x2}"))} }})",
                    $"\"{Escape(member.StringKey)}\"");
                EmitValueWrite(writer, member, (size, call) => Direct(size, call), Flush);
            }
        }

        Flush();
        if (model.UnknownMembersName is not null)
        {
            using (writer.Block("if (unknownMembers is not null)"))
            {
                writer.Line(model.IsStringKey
                    ? "buffer.WriteUnknownStringKeyed(unknownMembers);"
                    : model.Members.Length < model.MaxIntKey + 1
                        ? $"buffer.WriteUnknownIntKeyed(unknownMembers, {model.MaxIntKey + 1}, unknownReplayedCount);"
                        : $"buffer.WriteUnknownIntKeyed(unknownMembers, {model.MaxIntKey + 1});");
            }
        }
        writer.Line("state.Exit();");
    }

    static void EmitValueWrite(CodeWriter writer, MemberModel member, Action<string, string> direct, Action flush)
    {
        if (member.Direct == DirectKind.None)
        {
            flush();
            writer.Line($"f{member.Name}.Serialize(ref buffer, ref state, value.{member.Name});");
            return;
        }

        var access = $"value.{member.Name}";
        var (writeCall, size) = member.Direct switch
        {
            DirectKind.Int32 => ("UnsafeWriteInt32", "MaxInt32Length"),
            DirectKind.UInt32 => ("UnsafeWriteUInt32", "MaxUInt32Length"),
            DirectKind.Int64 => ("UnsafeWriteInt64", "MaxInt64Length"),
            DirectKind.UInt64 => ("UnsafeWriteUInt64", "MaxUInt64Length"),
            DirectKind.Int16 => ("UnsafeWriteInt16", "MaxInt16Length"),
            DirectKind.UInt16 => ("UnsafeWriteUInt16", "MaxUInt16Length"),
            DirectKind.Byte => ("UnsafeWriteByte", "MaxUInt8Length"),
            DirectKind.SByte => ("UnsafeWriteSByte", "MaxInt8Length"),
            DirectKind.Boolean => ("UnsafeWriteBoolean", "1"),
            DirectKind.Char => ("UnsafeWriteChar", "MaxUInt16Length"),
            DirectKind.Single => ("UnsafeWriteSingle", "MaxFloat32Length"),
            DirectKind.Double => ("UnsafeWriteDouble", "MaxFloat64Length"),
            _ => throw new InvalidOperationException(),
        };
        if (member.DirectNullable)
        {
            // nil (1 byte) stays under the primitive's max, so the reservation is the
            // same and the nil-or-value choice is one expression inside the fused run
            direct(size, $"{access} is {{ }} v{member.Name} ? {writeCall}({{DEST}}, v{member.Name}) : UnsafeWriteNil({{DEST}})");
            return;
        }
        direct(size, $"{writeCall}({{DEST}}, {access})");
    }

    static void EmitDeserialize(CodeWriter writer, ObjectModel model, string valueType)
    {
        // NoInlining keeps the formatter a standalone compilation unit. Measured (MapKeyEmitShapeBenchmark): when PGO devirtualizes the entry's formatter call and inlines this body into the caller, the inline budget starves the body's OWN callees (BinaryPrimitives reads, Advance, ReadString all stay real calls), costing 1.9x on map deserialize; pinned as a direct call, the body compiles clean and ties the best shape.
        writer.Line("[MethodImpl(MethodImplOptions.NoInlining)]");
        writer.Line($"public void Deserialize(ref TReadBuffer buffer, ref DeserializeState state, ref {valueType} value)");
        using (writer.OpenScope())
        {
            using (writer.Block("if (buffer.TryReadNil())"))
            {
                if (model.IsValueType)
                {
                    writer.Line($"throw new MessagePackSerializationException(\"code Nil cannot deserialize into the non-nullable struct '{model.FullTypeName}'.\");");
                }
                else
                {
                    writer.Line("value = null;");
                    writer.Line("return;");
                }
            }
            writer.Line();

            if (!model.UseConstruction)
            {
                if (model.AllowCircularReferences)
                {
                    using (writer.Block("if (buffer.TryReadCircularReferenceBackReference(out var circularReferenceId))"))
                    {
                        writer.Line($"value = state.ResolveCircularReference<{model.FullTypeName}>(circularReferenceId);");
                        writer.Line("return;");
                    }
                    writer.Line();
                    writer.Line("var envelopeCount = buffer.ReadArrayHeader();");
                    using (writer.Block("if (envelopeCount != 2)"))
                    {
                        writer.Line($"throw new MessagePackSerializationException(\"Deserializing '{model.FullTypeName}' expected the circular-reference envelope [id, body] (a 2-element array) but the array header claims \" + envelopeCount + \" elements\");");
                    }
                    writer.Line("var circularReferenceDefinitionId = buffer.ReadUInt32();");
                }
                writer.Line(model.IsValueType
                    ? "var result = value;"
                    : $"var result = value ?? new {model.FullTypeName}();");
                if (model.AllowCircularReferences)
                {
                    // register-before-populate: back-references inside the members below
                    // (a cycle) resolve to this in-progress instance
                    writer.Line("state.RegisterCircularReference(circularReferenceDefinitionId, result);");
                }
                writer.Line("state.Enter();");
                writer.Line();
                EmitReadLoop(writer, model, EmitPopulateRead);
                EmitUnknownMembersAssign(writer, model);
                writer.Line("state.Exit();");
                EmitCallback(writer, model.OnAfterDeserialize, model, "result", "OnAfterDeserialize");
                writer.Line("value = result;");
            }
            else if (!model.IsValueType)
            {
                // construction shape, reference type: a caller-supplied instance keeps populate
                // semantics — ReflectionObjectFormatter's Arguments-mode rule — with non-settable
                // payloads skipped, so the type carries TWO read loops with different leaf programs.
                // Each lives in its own NoInlining helper: the fresh path must not carry the populate
                // automata in its compilation unit (an unexecuted sibling block in the same method
                // measurably slows the executed loop — ArrayDeserializeShapeBenchmark round 1).
                using (writer.Block("if (value is not null)"))
                {
                    writer.Line("DeserializePopulate(ref buffer, ref state, value);");
                    writer.Line("return;");
                }
                writer.Line("value = DeserializeConstruct(ref buffer, ref state);");
            }
            else
            {
                // structs have no identity to preserve and always reconstruct
                EmitConstructCore(writer, model);
                writer.Line("value = constructed;");
            }
        }

        if (model.UseConstruction && !model.IsValueType)
        {
            writer.Line();
            writer.Line("[MethodImpl(MethodImplOptions.NoInlining)]");
            writer.Line($"void DeserializePopulate(ref TReadBuffer buffer, ref DeserializeState state, {model.FullTypeName} result)");
            using (writer.OpenScope())
            {
                writer.Line("state.Enter();");
                writer.Line();
                EmitReadLoop(writer, model, EmitPopulateRead);
                EmitUnknownMembersAssign(writer, model);
                writer.Line("state.Exit();");
                EmitCallback(writer, model.OnAfterDeserialize, model, "result", "OnAfterDeserialize");
            }

            writer.Line();
            writer.Line("[MethodImpl(MethodImplOptions.NoInlining)]");
            writer.Line($"{model.FullTypeName} DeserializeConstruct(ref TReadBuffer buffer, ref DeserializeState state)");
            using (writer.OpenScope())
            {
                EmitConstructCore(writer, model);
                writer.Line("return constructed;");
            }
        }
    }

    // construction core: read into locals, then invoke the matched constructor and assign the
    // rest through an object initializer (which is how init-only members are reachable).
    // Leaves `constructed` in scope for the caller to consume.
    static void EmitConstructCore(CodeWriter writer, ObjectModel model)
    {
        foreach (var member in model.Members)
        {
            if (!IsSkippedOnConstruction(member))
            {
                writer.Line($"{member.TypeName} v_{member.Name} = default!;");
            }
        }
        writer.Line("state.Enter();");
        writer.Line();
        EmitReadLoop(writer, model, EmitLocalRead);
        writer.Line("state.Exit();");

        var arguments = new string[model.ConstructorParameterCount];
        var initializers = new List<string>();
        foreach (var member in model.Members)
        {
            if (member.ConstructorParameterIndex >= 0)
            {
                arguments[member.ConstructorParameterIndex] = $"v_{member.Name}";
                if (member.HasRequiredModifier && !model.ConstructorSetsRequiredMembers && member.Setter != SetterKind.None)
                {
                    // the constructor consumes the value but does not declare
                    // [SetsRequiredMembers]: the compiler still demands an object
                    // initializer assignment for the required member (CS9035)
                    initializers.Add($"{member.Name} = v_{member.Name}");
                }
            }
            else if (member.Setter != SetterKind.None)
            {
                initializers.Add($"{member.Name} = v_{member.Name}");
            }
        }
        if (model.UnknownMembersName is { } unknownName)
        {
            initializers.Add($"{unknownName} = unknownMembers");
        }
        var construction = $"var constructed = new {model.FullTypeName}({string.Join(", ", arguments)})";
        if (initializers.Count > 0)
        {
            writer.Line(construction);
            using (writer.OpenScope(closeSuffix: ";"))
            {
                foreach (var initializer in initializers)
                {
                    writer.Line($"{initializer},");
                }
            }
        }
        else
        {
            writer.Line(construction + ";");
        }
        EmitCallback(writer, model.OnAfterDeserialize, model, "constructed", "OnAfterDeserialize");
    }

    // populate paths assign unconditionally: null when nothing was captured, so a reused
    // instance never keeps a stale packet from a previous deserialization
    static void EmitUnknownMembersAssign(CodeWriter writer, ObjectModel model)
    {
        if (model.UnknownMembersName is { } unknownName)
        {
            writer.Line($"result.{unknownName} = unknownMembers;");
        }
    }

    static bool IsSkippedOnConstruction(MemberModel member) =>
        member.Setter == SetterKind.None && member.ConstructorParameterIndex < 0;

    static bool AnyRequired(ObjectModel model) => model.Members.AsArray().Any(static m => m.IsRequired);

    // a member gets a null check only where its value is actually observed: through the
    // setter on the populate path, through the local on the construction path
    static bool NeedsNullCheckOnPopulate(MemberModel member) =>
        member.Direct == DirectKind.None && member.IsNonNullableReference && member.Setter == SetterKind.Set;

    static bool NeedsNullCheckOnLocal(MemberModel member) =>
        member.Direct == DirectKind.None && member.IsNonNullableReference && !IsSkippedOnConstruction(member);

    static bool AnyNullCheck(ObjectModel model) => model.UseConstruction
        ? model.Members.AsArray().Any(NeedsNullCheckOnLocal)
        : model.Members.AsArray().Any(NeedsNullCheckOnPopulate);

    // populate path: assign through the setter; a member without one skips its payload
    // (the reflection tier's relaxation for serialize-only members). Init-only members
    // land here only via the caller-supplied-instance branch, where they are likewise
    // unreachable and skipped.
    static void EmitPopulateRead(CodeWriter writer, MemberModel member)
    {
        if (member.Setter != SetterKind.Set)
        {
            writer.Line("buffer.Skip();");
            return;
        }
        if (member.Direct == DirectKind.None)
        {
            using (writer.OpenScope())
            {
                writer.Line($"var v = result.{member.Name};");
                writer.Line($"f{member.Name}.Deserialize(ref buffer, ref state, ref v);");
                if (NeedsNullCheckOnPopulate(member))
                {
                    writer.Line($"if (validateNull && v is null) {{ ThrowNullValueForNonNullableMember(\"{member.Name}\"); }}");
                }
                writer.Line($"result.{member.Name} = v;");
            }
            return;
        }
        writer.Line(member.DirectNullable
            ? $"result.{member.Name} = buffer.TryReadNil() ? default({member.TypeName}) : buffer.{Reader(member.Direct)}();"
            : $"result.{member.Name} = buffer.{Reader(member.Direct)}();");
    }

    static void EmitLocalRead(CodeWriter writer, MemberModel member)
    {
        if (IsSkippedOnConstruction(member))
        {
            writer.Line("buffer.Skip();");
            return;
        }
        writer.Line(member.Direct == DirectKind.None
            ? $"f{member.Name}.Deserialize(ref buffer, ref state, ref v_{member.Name});"
            : member.DirectNullable
                ? $"v_{member.Name} = buffer.TryReadNil() ? default({member.TypeName}) : buffer.{Reader(member.Direct)}();"
                : $"v_{member.Name} = buffer.{Reader(member.Direct)}();");
        if (NeedsNullCheckOnLocal(member))
        {
            writer.Line($"if (validateNull && v_{member.Name} is null) {{ ThrowNullValueForNonNullableMember(\"{member.Name}\"); }}");
        }
    }

    static string Reader(DirectKind direct) => direct switch
    {
        DirectKind.Int32 => "ReadInt32",
        DirectKind.UInt32 => "ReadUInt32",
        DirectKind.Int64 => "ReadInt64",
        DirectKind.UInt64 => "ReadUInt64",
        DirectKind.Int16 => "ReadInt16",
        DirectKind.UInt16 => "ReadUInt16",
        DirectKind.Byte => "ReadByte",
        DirectKind.SByte => "ReadSByte",
        DirectKind.Boolean => "ReadBoolean",
        DirectKind.Char => "ReadChar",
        DirectKind.Single => "ReadSingle",
        DirectKind.Double => "ReadDouble",
        _ => throw new InvalidOperationException(),
    };

    static void EmitReadLoop(CodeWriter writer, ObjectModel model, Action<CodeWriter, MemberModel> emitMemberRead)
    {
        if (model.UnknownMembersName is not null)
        {
            writer.Line("MessagePackUnknownMembers? unknownMembers = null;");
        }
        if (!model.IsStringKey)
        {
            writer.Line("var count = buffer.ReadArrayHeader();");
            using (writer.Block("for (int i = 0; i < count; i++)"))
            using (writer.Block("switch (i)"))
            {
                foreach (var member in model.Members)
                {
                    writer.Line($"case {member.IntKey}:");
                    writer.Indent();
                    emitMemberRead(writer, member);
                    writer.Line("break;");
                    writer.Unindent();
                }
                writer.Line("default:");
                writer.Indent();
                if (model.UnknownMembersName is not null)
                {
                    using (writer.Block($"if (i > {model.MaxIntKey})"))
                    {
                        writer.Line("buffer.CaptureUnknownIntKeyed(ref unknownMembers, i);");
                    }
                    using (writer.Block("else"))
                    {
                        // key hole: nil is the padding serialize regenerates and is not
                        // captured (the type's own payloads stay packet-free); anything
                        // else is a wider writer's value at a key this schema retired
                        // by deleting the member, held for replay at the same index
                        writer.Line("buffer.CaptureUnknownIntKeyedHole(ref unknownMembers, i);");
                    }
                }
                else
                {
                    writer.Line("buffer.Skip(); // version tolerance: unknown trailing member");
                }
                writer.Line("break;");
                writer.Unindent();
            }
            if (AnyRequired(model))
            {
                // presence in the array form is positional: every required key must lie
                // below count (an explicit nil slot counts as present; nil VALUES are the
                // nullable check's business)
                var requiredCount = model.Members.AsArray().Where(static m => m.IsRequired).Max(static m => m.IntKey) + 1;
                using (writer.Block($"if (validateRequired && count < {requiredCount})"))
                {
                    writer.Line("ThrowMissingRequiredMember(count);");
                }
            }
            writer.Line();
            return;
        }

        writer.Line("var count = buffer.ReadMapHeader();");
        // duplicate map keys are data errors (same policy as the dictionary formatters);
        // the member index is a compile-time constant, so the common <=64-member case
        // is a constant bitmask test and or. The wide tier (>64) is Span-typed either way:
        // stackalloc up to 256 members (the added recursion-frame cost stays within the
        // method's own frame order; MaxDepth bounds recursion), heap array beyond. The
        // stackalloc gets an explicit Clear() instead of relying on locals-init zeroing —
        // generated code compiles into the USER's assembly, where a module-level
        // [SkipLocalsInit] would otherwise hand the tracker garbage and fail legitimate
        // payloads as duplicate keys.
        var wideMemberTable = model.Members.Length > 64;
        if (wideMemberTable && model.Members.Length <= StackallocSeenMembersLimit)
        {
            writer.Line($"global::System.Span<bool> seenMembers = stackalloc bool[{model.Members.Length}];");
            writer.Line("seenMembers.Clear();");
        }
        else if (wideMemberTable)
        {
            writer.Line($"global::System.Span<bool> seenMembers = new bool[{model.Members.Length}];");
        }
        else
        {
            writer.Line("ulong seenMembers = 0;");
        }
        // the emitted key loop compares utf8 in place BEFORE Advance (the span may alias a
        // pooled stitch buffer), and TryGetSpan false = truncated key payload: the domain
        // exception is thrown in the generated code, the foundation never throws for truncation
        using (writer.Block("for (int i = 0; i < count; i++)"))
        {
            writer.Line("var byteCount = buffer.ReadStringHeader();");
            using (writer.Block("if (!buffer.TryGetSpan(byteCount, out var key))"))
            {
                writer.Line("throw new MessagePackSerializationException(\"Unexpected end of data while reading a map key.\");");
            }
            writer.Line("key = key.Slice(0, byteCount);");
            writer.Line();

            EmitStringKeyAutomata(writer, model, wideMemberTable, emitMemberRead);
            writer.Line();
            if (model.UnknownMembersName is not null)
            {
                // key is still in place (pre-Advance): the capture copies it before the
                // window can be recycled, then consumes the value verbatim
                writer.Line("buffer.CaptureUnknownStringKeyed(ref unknownMembers, key);");
            }
            else
            {
                writer.Line("buffer.Advance(byteCount);");
                writer.Line("buffer.Skip(); // version tolerance: unknown key's value");
            }
        }
        if (AnyRequired(model))
        {
            var requiredIndexes = RequiredMemberIndexes(model);
            if (wideMemberTable)
            {
                var anyMissing = string.Join(" || ", requiredIndexes.Select(static i => $"!seenMembers[{i}]"));
                using (writer.Block($"if (validateRequired && ({anyMissing}))"))
                {
                    writer.Line("ThrowMissingRequiredMember(seenMembers);");
                }
            }
            else
            {
                var mask = RequiredMask(requiredIndexes);
                using (writer.Block($"if (validateRequired && (seenMembers & {mask}) != {mask})"))
                {
                    writer.Line("ThrowMissingRequiredMember(seenMembers);");
                }
            }
        }
        writer.Line();
    }

    // Length-first embedded automata for the string-key match (MapKeyMatchBenchmark, 16 members: 1.20ns/key in-order vs 3.87 for the SequenceEqual chain).
    // The root switch pins the key length, so every compare is an exact-width little-endian constant (the JIT only unrolls SequenceEqual for literals <= 8 bytes; longer keys were paying real calls), lengths absent from the member set reject with zero compares, and chunk-first automata lose on tail composition (measured 1.91).
    // A declaration-order hint was also measured and refuted: its dispatch costs as much as the length switch it tries to skip.
    // A matched leaf runs its member read and continues the key loop; every fall-through path reaches the caller's unknown-key skip.
    static void EmitStringKeyAutomata(CodeWriter writer, ObjectModel model, bool wideMemberTable, Action<CodeWriter, MemberModel> emitMemberRead)
    {
        // first declaration wins on duplicate keys, mirroring the old first-match chain
        var entries = new List<(MemberModel Member, int Index, byte[] Utf8)>();
        var seenKeys = new HashSet<string>();
        for (int index = 0; index < model.Members.Length; index++)
        {
            var member = model.Members[index];
            if (seenKeys.Add(member.StringKey))
            {
                entries.Add((member, index, Encoding.UTF8.GetBytes(member.StringKey)));
            }
        }
        if (entries.Count == 0)
        {
            return; // memberless map type: every key takes the unknown-key skip
        }

        using (writer.Block("switch (byteCount)"))
        {
            foreach (var bucket in entries.GroupBy(static e => e.Utf8.Length).OrderBy(static g => g.Key))
            {
                writer.Line($"case {bucket.Key}:");
                writer.Indent();
                EmitLengthBucket(writer, [.. bucket], bucket.Key, wideMemberTable, emitMemberRead);
                writer.Unindent();
            }
        }
    }

    static void EmitLengthBucket(CodeWriter writer, (MemberModel Member, int Index, byte[] Utf8)[] bucket, int length, bool wideMemberTable, Action<CodeWriter, MemberModel> emitMemberRead)
    {
        var reads = PlanKeyReads(length);

        if (bucket.Length == 1)
        {
            var (member, index, utf8) = bucket[0];
            if (reads.Count == 0)
            {
                // the empty key: the length alone identifies it, the leaf's continue ends the case
                EmitKeyLeaf(writer, member, index, wideMemberTable, emitMemberRead);
                return;
            }
            using (writer.Block($"if ({KeyCondition(utf8, reads, 0)}) // \"{Escape(member.StringKey)}\""))
            {
                EmitKeyLeaf(writer, member, index, wideMemberTable, emitMemberRead);
            }
            writer.Line("break;");
            return;
        }

        // several members share this length: discriminate on the first chunk, compare the rest inside
        var (offset0, width0) = reads[0];
        using (writer.Block($"switch ({KeyReadExpr(offset0, width0)})"))
        {
            foreach (var group in bucket.GroupBy(e => KeyConst(e.Utf8, offset0, width0)))
            {
                writer.Line($"case {KeyConstLiteral(group.Key, width0)}:");
                writer.Indent();
                var closed = false;
                foreach (var (member, index, utf8) in group)
                {
                    if (reads.Count == 1)
                    {
                        // one full-width read is the whole key: distinct members cannot share it, the leaf's continue ends the case
                        writer.Line($"// \"{Escape(member.StringKey)}\"");
                        EmitKeyLeaf(writer, member, index, wideMemberTable, emitMemberRead);
                        closed = true;
                    }
                    else
                    {
                        using (writer.Block($"if ({KeyCondition(utf8, reads, 1)}) // \"{Escape(member.StringKey)}\""))
                        {
                            EmitKeyLeaf(writer, member, index, wideMemberTable, emitMemberRead);
                        }
                    }
                }
                if (!closed)
                {
                    writer.Line("break;");
                }
                writer.Unindent();
            }
        }
        writer.Line("break;");
    }

    static void EmitKeyLeaf(CodeWriter writer, MemberModel member, int memberIndex, bool wideMemberTable, Action<CodeWriter, MemberModel> emitMemberRead)
    {
        writer.Line("buffer.Advance(byteCount);");
        if (wideMemberTable)
        {
            writer.Line($"if (seenMembers[{memberIndex}]) {{ throw new MessagePackSerializationException(\"The map in the payload defines the same key more than once\"); }}");
            writer.Line($"seenMembers[{memberIndex}] = true;");
        }
        else
        {
            writer.Line($"if ((seenMembers & (1UL << {memberIndex})) != 0) {{ throw new MessagePackSerializationException(\"The map in the payload defines the same key more than once\"); }}");
            writer.Line($"seenMembers |= 1UL << {memberIndex};");
        }
        emitMemberRead(writer, member);
        writer.Line("continue;");
    }

    // constant-width reads covering [0, length): the widest fitting width strides forward, an overlapped tail read finishes the remainder.
    // Overlap never leaves the key (the span is sliced to exactly byteCount), and full coverage means equal reads imply equal keys.
    static List<(int Offset, int Width)> PlanKeyReads(int length)
    {
        var reads = new List<(int Offset, int Width)>();
        if (length == 0)
        {
            return reads;
        }
        int width = length >= 8 ? 8 : length >= 4 ? 4 : length >= 2 ? 2 : 1;
        int offset = 0;
        for (; offset + width <= length; offset += width)
        {
            reads.Add((offset, width));
        }
        if (offset < length)
        {
            reads.Add((length - width, width));
        }
        return reads;
    }

    static string KeyCondition(byte[] utf8, List<(int Offset, int Width)> reads, int fromRead) =>
        string.Join(" && ", reads.Skip(fromRead).Select(r => $"{KeyReadExpr(r.Offset, r.Width)} == {KeyConstLiteral(KeyConst(utf8, r.Offset, r.Width), r.Width)}"));

    static ulong KeyConst(byte[] utf8, int offset, int width)
    {
        ulong value = 0;
        for (int i = 0; i < width; i++)
        {
            value |= (ulong)utf8[offset + i] << (8 * i);
        }
        return value;
    }

    static string KeyReadExpr(int offset, int width)
    {
        var span = offset == 0 ? "key" : $"key.Slice({offset})";
        return width switch
        {
            8 => $"BinaryPrimitives.ReadUInt64LittleEndian({span})",
            4 => $"BinaryPrimitives.ReadUInt32LittleEndian({span})",
            2 => $"BinaryPrimitives.ReadUInt16LittleEndian({span})",
            _ => $"key[{offset}]",
        };
    }

    static string KeyConstLiteral(ulong value, int width) => width switch
    {
        8 => $"0x{value:x16}UL",
        4 => $"0x{value:x8}U",
        2 => $"0x{value:x4}",
        _ => $"0x{value:x2}",
    };

    // positions inside model.Members: the same indexing the seenMembers ledger uses
    static int[] RequiredMemberIndexes(ObjectModel model)
    {
        var indexes = new List<int>();
        for (int i = 0; i < model.Members.Length; i++)
        {
            if (model.Members[i].IsRequired)
            {
                indexes.Add(i);
            }
        }
        return [.. indexes];
    }

    static string RequiredMask(int[] requiredIndexes)
    {
        ulong mask = 0;
        foreach (var index in requiredIndexes)
        {
            mask |= 1UL << index;
        }
        return $"0x{mask:x}UL";
    }

    // the helpers are cold by design: one method per formatter names the first missing /
    // null member, so the hot loop carries only a flag test and a call
    static void EmitRequiredThrowHelper(CodeWriter writer, ObjectModel model)
    {
        writer.Line("[MethodImpl(MethodImplOptions.NoInlining)]");
        string selector;
        if (!model.IsStringKey)
        {
            writer.Line("static void ThrowMissingRequiredMember(int count)");
            var ordered = model.Members.AsArray().Where(static m => m.IsRequired).OrderBy(static m => m.IntKey).ToArray();
            selector = BuildMemberSelector(ordered, static m => $"count <= {m.IntKey}");
        }
        else
        {
            var requiredIndexes = RequiredMemberIndexes(model);
            var required = requiredIndexes.Select(i => (Index: i, Member: model.Members[i])).ToArray();
            if (model.Members.Length > 64)
            {
                writer.Line("static void ThrowMissingRequiredMember(global::System.ReadOnlySpan<bool> seenMembers)");
                selector = BuildMemberSelector(required, static r => $"!seenMembers[{r.Index}]", static r => r.Member);
            }
            else
            {
                writer.Line("static void ThrowMissingRequiredMember(ulong seenMembers)");
                selector = BuildMemberSelector(required, static r => $"(seenMembers & 0x{1UL << r.Index:x}UL) == 0", static r => r.Member);
            }
        }
        using (writer.OpenScope())
        {
            writer.Line($"var member = {selector};");
            writer.Line($"throw new MessagePackSerializationException(\"Required member '\" + member + \"' of '{model.FullTypeName}' is missing from the payload (required member validation, MessagePackFormatterResolver validateRequiredMembers, on by default)\");");
        }
    }

    static string BuildMemberSelector(MemberModel[] members, Func<MemberModel, string> condition) =>
        BuildMemberSelector(members, condition, static m => m);

    // conditional chain naming the first missing member; the last candidate needs no
    // condition because the helper only runs when at least one is missing
    static string BuildMemberSelector<TItem>(TItem[] items, Func<TItem, string> condition, Func<TItem, MemberModel> member)
    {
        var parts = new List<string>();
        for (int i = 0; i < items.Length - 1; i++)
        {
            parts.Add($"{condition(items[i])} ? \"{member(items[i]).Name}\" :");
        }
        parts.Add($"\"{member(items[items.Length - 1]).Name}\"");
        return string.Join(" ", parts);
    }

    static void EmitNullThrowHelper(CodeWriter writer, ObjectModel model)
    {
        writer.Line("[MethodImpl(MethodImplOptions.NoInlining)]");
        writer.Line("static void ThrowNullValueForNonNullableMember(string member)");
        using (writer.OpenScope())
        {
            writer.Line($"throw new MessagePackSerializationException(\"Member '\" + member + \"' of '{model.FullTypeName}' is declared non-nullable but the payload contains nil (nullable annotation validation, MessagePackFormatterResolver validateNullableAnnotations)\");");
        }
    }

    static void EmitCallback(CodeWriter writer, CallbackStyle style, ObjectModel model, string target, string method)
    {
        switch (style)
        {
            case CallbackStyle.None:
                return;
            case CallbackStyle.Direct:
                writer.Line($"{target}.{method}();");
                return;
            default:
                if (model.IsValueType)
                {
                    // explicit implementation on a struct: the helper's constrained call
                    // dispatches on the local's address, no box, mutations land in place
                    writer.Line($"global::MessagePack.SourceGeneratorHelper.{method}(ref {target});");
                }
                else
                {
                    writer.Line($"((global::MessagePack.IMessagePackSerializationCallbackReceiver){target}).{method}();");
                }
                return;
        }
    }

    // msgpack str token (smallest header + utf8 payload) pre-encoded at generator time
    static byte[] EncodeStringKeyBlob(string key)
    {
        var utf8 = Encoding.UTF8.GetBytes(key);
        var n = utf8.Length;
        byte[] header = n switch
        {
            <= 31 => [(byte)(0xa0 | n)],
            <= byte.MaxValue => [0xd9, (byte)n],
            <= ushort.MaxValue => [0xda, (byte)(n >> 8), (byte)n],
            _ => [0xdb, (byte)(n >> 24), (byte)(n >> 16), (byte)(n >> 8), (byte)n],
        };
        var blob = new byte[header.Length + n];
        header.CopyTo(blob, 0);
        utf8.CopyTo(blob, header.Length);
        return blob;
    }

    static string Escape(string value)
    {
        var builder = new StringBuilder(value.Length);
        foreach (var c in value)
        {
            switch (c)
            {
                case '"': builder.Append("\\\""); break;
                case '\\': builder.Append("\\\\"); break;
                case '\n': builder.Append("\\n"); break;
                case '\r': builder.Append("\\r"); break;
                case '\t': builder.Append("\\t"); break;
                case '\0': builder.Append("\\0"); break;
                default: builder.Append(c); break;
            }
        }
        return builder.ToString();
    }
}
