namespace MessagePack.SourceGenerator;

/// <summary>
/// Emits the polymorphism formatter for a [Union] base, MessagePack-CSharp wire form:
/// fixarray(2) of [int tag, case payload]; nil for null. An untagged runtime type
/// THROWS on serialize (a v4 deviation from v3's silent nil: the writer knows its own
/// type set, so an untagged value is a declaration bug, not version skew — this is the
/// runtime backstop for the open hierarchies MsgPack106 cannot see). An unknown tag on read
/// still skips its payload and yields null — that one is genuine version tolerance
/// (newer writer, older reader), kept from the v3 UnionResolver.
/// A pattern union (a C# union declaration, or a hand-written [Union]-pattern type) rides
/// the same wire: the held case is read through the non-boxing TryGetValue accessors when
/// the union declares them for every tagged case, through Value otherwise (via the
/// IUnionMembers provider interface when the union delegates its members there), and goes
/// back in through the creation members (per-case constructor, or IUnionMembers.Create).
/// For a struct root every null/unknown outcome becomes default(TUnion) — whose Value is
/// null, so the nil round-trip stays symmetric.
/// </summary>
static class UnionEmitter
{
    public static string EmitFormatter(UnionModel model)
    {
        var writer = CodeWriter.Rent();
        var valueType = model.IsStructRoot ? model.FullTypeName : model.FullTypeName + "?";

        writer.Line("// <auto-generated/>");
        writer.Line("#nullable enable annotations");
        writer.Line("using SerializerFoundation;");
        writer.Line("using MessagePack;");
        writer.Line();
        var ns = writer.Block("namespace MessagePack.Generated");

        var formatterTypeParameters = model.TypeParameterList.Length == 0
            ? "TWriteBuffer, TReadBuffer"
            : "TWriteBuffer, TReadBuffer, " + model.TypeParameterList;
        writer.Line($"internal sealed class {model.FormatterName}<{formatterTypeParameters}> : IMessagePackFormatter<TWriteBuffer, TReadBuffer, {valueType}>");
        writer.Indent();
        ObjectEmitter.EmitBufferConstraints(writer);
        foreach (var clause in model.WhereClauses)
        {
            writer.Line(clause);
        }
        writer.Unindent();
        var body = writer.OpenScope();

        foreach (var unionCase in model.Cases)
        {
            writer.Line($"IMessagePackFormatter<TWriteBuffer, TReadBuffer, {CaseValueType(unionCase)}> {unionCase.FieldName} = null!;");
        }

        writer.Line();
        writer.Line("public void Initialize(MessagePackFormatterResolver resolver)");
        using (writer.OpenScope())
        {
            foreach (var unionCase in model.Cases)
            {
                writer.Line($"{unionCase.FieldName} = resolver.GetFormatter<TWriteBuffer, TReadBuffer, {CaseValueType(unionCase)}>();");
            }
        }

        // union members live on the provider interface when one exists; the cast is an
        // interface access (boxes a struct union, but provider unions are class-shaped)
        var access = model.ProviderInterface is null ? "value" : $"(({model.ProviderInterface})value)";

        writer.Line();
        writer.Line($"public void Serialize(ref TWriteBuffer buffer, ref SerializeState state, {valueType} value)");
        using (writer.OpenScope())
        {
            if (!model.IsStructRoot)
            {
                using (writer.Block("if (value == null)"))
                {
                    writer.Line("buffer.WriteNil();");
                    writer.Line("return;");
                }
            }
            if (model.UseNonBoxing)
            {
                // TryGetValue dispatch: strongly typed access, no Value boxing; the final
                // else covers both a null-held union and an untagged held case
                writer.Line("state.Enter();");
                var caseIndex = 0;
                var first = true;
                foreach (var unionCase in model.Cases)
                {
                    var keyword = first ? "if" : "else if";
                    first = false;
                    using (writer.Block($"{keyword} ({access}.TryGetValue(out {unionCase.TypeName} case{caseIndex}))"))
                    {
                        writer.Line("buffer.WriteArrayHeader(2);");
                        writer.Line($"buffer.WriteInt32({unionCase.Tag});");
                        writer.Line($"{unionCase.FieldName}.Serialize(ref buffer, ref state, case{caseIndex});");
                    }
                    caseIndex++;
                }
                using (writer.Block($"else if ({access}.Value == null)"))
                {
                    writer.Line("buffer.WriteNil();");
                }
                using (writer.Block("else"))
                {
                    // Value is only read on this cold miss path; the tagged cases stay
                    // on the non-boxing TryGetValue dispatch above
                    writer.Line($"throw new MessagePackSerializationException($\"Runtime type '{{{access}.Value!.GetType()}}' is not a [UnionTag] case of '{model.FullTypeName}'.\");");
                }
                writer.Line("state.Exit();");
            }
            else
            {
                var heldValue = model.IsPatternUnion ? "heldValue" : "value";
                if (model.IsPatternUnion)
                {
                    writer.Line($"var heldValue = {access}.Value;");
                    using (writer.Block("if (heldValue == null)"))
                    {
                        writer.Line("buffer.WriteNil();");
                        writer.Line("return;");
                    }
                }
                writer.Line("state.Enter();");
                if (model.TypeParameterList.Length > 0)
                {
                    // generic roots cannot dispatch on exact runtime type (a case may BE a
                    // type parameter): `is` matching in attribute order decides, so an
                    // instance assignable to several cases takes the first tag
                    var caseIndex = 0;
                    var first = true;
                    foreach (var unionCase in model.Cases)
                    {
                        var keyword = first ? "if" : "else if";
                        first = false;
                        using (writer.Block($"{keyword} ({heldValue} is {unionCase.TypeName} case{caseIndex})"))
                        {
                            writer.Line("buffer.WriteArrayHeader(2);");
                            writer.Line($"buffer.WriteInt32({unionCase.Tag});");
                            writer.Line($"{unionCase.FieldName}.Serialize(ref buffer, ref state, case{caseIndex});");
                        }
                        caseIndex++;
                    }
                    using (writer.Block("else"))
                    {
                        writer.Line($"throw new MessagePackSerializationException($\"Runtime type '{{{heldValue}.GetType()}}' is not a [UnionTag] case of '{model.FullTypeName}'.\");");
                    }
                }
                else
                {
                    writer.Line($"var runtimeType = {heldValue}.GetType();");
                    var first = true;
                    foreach (var unionCase in model.Cases)
                    {
                        var keyword = first ? "if" : "else if";
                        first = false;
                        using (writer.Block($"{keyword} (runtimeType == typeof({unionCase.TypeName}))"))
                        {
                            writer.Line("buffer.WriteArrayHeader(2);");
                            writer.Line($"buffer.WriteInt32({unionCase.Tag});");
                            writer.Line($"{unionCase.FieldName}.Serialize(ref buffer, ref state, ({unionCase.TypeName}){heldValue});");
                        }
                    }
                    using (writer.Block("else"))
                    {
                        writer.Line($"throw new MessagePackSerializationException($\"Runtime type '{{runtimeType}}' is not a [UnionTag] case of '{model.FullTypeName}'.\");");
                    }
                }
                writer.Line("state.Exit();");
            }
        }

        var emptyValue = model.IsStructRoot ? "default" : "null";
        writer.Line();
        writer.Line($"public void Deserialize(ref TReadBuffer buffer, ref DeserializeState state, ref {valueType} value)");
        using (writer.OpenScope())
        {
            using (writer.Block("if (buffer.TryReadNil())"))
            {
                writer.Line($"value = {emptyValue};");
                writer.Line("return;");
            }
            writer.Line("state.Enter();");
            using (writer.Block("if (buffer.ReadArrayHeader() != 2)"))
            {
                writer.Line("throw new MessagePackSerializationException(\"Invalid Union data was detected.\");");
            }
            using (writer.Block("switch (buffer.ReadInt32())"))
            {
                foreach (var unionCase in model.Cases)
                {
                    writer.Line($"case {unionCase.Tag}:");
                    using (writer.OpenScope())
                    {
                        if (model.IsPatternUnion)
                        {
                            // a union value is replaced wholesale, so the case deserializes
                            // into a fresh default and rides a creation member back in
                            writer.Line($"{CaseValueType(unionCase)} v = default!;");
                            writer.Line($"{unionCase.FieldName}.Deserialize(ref buffer, ref state, ref v);");
                            writer.Line(model.ProviderInterface is null
                                ? $"value = new {model.FullTypeName}(v!);"
                                : $"value = {model.ProviderInterface}.Create(v!);");
                        }
                        else
                        {
                            writer.Line(unionCase.IsValueType
                                ? $"var v = value is {unionCase.TypeName} existing ? existing : default;"
                                : $"var v = value as {unionCase.TypeName};");
                            writer.Line($"{unionCase.FieldName}.Deserialize(ref buffer, ref state, ref v);");
                            writer.Line("value = v;");
                        }
                        writer.Line("break;");
                    }
                }
                writer.Line("default:");
                writer.Indent();
                writer.Line("buffer.Skip(); // version tolerance: unknown case tag");
                writer.Line($"value = {emptyValue};");
                writer.Line("break;");
                writer.Unindent();
            }
            writer.Line("state.Exit();");
        }

        body.Dispose();
        ns.Dispose();
        return writer.ToStringAndReturn();
    }

    static string CaseValueType(UnionCaseModel unionCase) =>
        unionCase.IsValueType ? unionCase.TypeName : unionCase.TypeName + "?";
}
