// <auto-generated />

#pragma warning disable 618, 612, 414, 168, CS1591, SA1129, SA1309, SA1312, SA1403, SA1649

#pragma warning disable CS8669 // We may leak nullable annotations into generated code.

using MsgPack = global::MessagePack;

namespace MessagePack {
internal partial class GeneratedMessagePackResolver {

	internal sealed class SampleObjectFormatter : MsgPack::Formatters.IMessagePackFormatter<global::SampleObject>
	{

		public void Serialize(ref MsgPack::MessagePackWriter writer, global::SampleObject value, MsgPack::MessagePackSerializerOptions options)
		{
			if (value == null)
			{
				writer.WriteNil();
				return;
			}

			writer.WriteArrayHeader(5);
			MsgPack::FormatterResolverExtensions.SerializeWithVerifyByRef<(bool, byte, sbyte)>(ref writer, value.Value1, options);
			MsgPack::FormatterResolverExtensions.SerializeWithVerifyByRef<(short, ushort, int, uint)>(ref writer, value.Value2, options);
			MsgPack::FormatterResolverExtensions.SerializeWithVerifyByRef<(long, ulong, float, double)>(ref writer, value.Value3, options);
			MsgPack::FormatterResolverExtensions.SerializeWithVerifyByRef<(decimal, char, string, object)>(ref writer, value.Value4, options);
			MsgPack::FormatterResolverExtensions.SerializeWithVerifyByRef<global::System.ValueTuple<int?>>(ref writer, value.Value5, options);
		}

		public global::SampleObject Deserialize(ref MsgPack::MessagePackReader reader, MsgPack::MessagePackSerializerOptions options)
		{
			if (reader.TryReadNil())
			{
				return null;
			}

			options.Security.DepthStep(ref reader);
			var length = reader.ReadArrayHeader();
			var ____result = new global::SampleObject();

			for (int i = 0; i < length; i++)
			{
				switch (i)
				{
					case 0:
						____result.Value1 = MsgPack::FormatterResolverExtensions.DeserializeWithVerifyByRef<(bool, byte, sbyte)>(ref reader, options);
						break;
					case 1:
						____result.Value2 = MsgPack::FormatterResolverExtensions.DeserializeWithVerifyByRef<(short, ushort, int, uint)>(ref reader, options);
						break;
					case 2:
						____result.Value3 = MsgPack::FormatterResolverExtensions.DeserializeWithVerifyByRef<(long, ulong, float, double)>(ref reader, options);
						break;
					case 3:
						____result.Value4 = MsgPack::FormatterResolverExtensions.DeserializeWithVerifyByRef<(decimal, char, string, object)>(ref reader, options);
						break;
					case 4:
						____result.Value5 = MsgPack::FormatterResolverExtensions.DeserializeWithVerifyByRef<global::System.ValueTuple<int?>>(ref reader, options);
						break;
					default:
						reader.Skip();
						break;
				}
			}

			reader.Depth--;
			return ____result;
		}
	}
}
}
