// <auto-generated />

#pragma warning disable 618, 612, 414, 168, CS1591, SA1129, SA1309, SA1312, SA1403, SA1649

namespace Formatters
{
	using MsgPack = global::MessagePack;
	using ContainingClass_MyEnum = global::ContainingClass.MyEnum;

	internal sealed class ContainingClass_MyEnumFormatter : MsgPack::Formatters.IMessagePackFormatter<ContainingClass_MyEnum>
	{
		public void Serialize(ref MsgPack::MessagePackWriter writer, ContainingClass_MyEnum value, MsgPack::MessagePackSerializerOptions options)
		{
			writer.Write((int)value);
		}

		public ContainingClass_MyEnum Deserialize(ref MsgPack::MessagePackReader reader, MsgPack::MessagePackSerializerOptions options)
		{
			return (ContainingClass_MyEnum)reader.ReadInt32();
		}
	}
}
