// <auto-generated />

#pragma warning disable 618, 612, 414, 168, CS1591, SA1129, SA1309, SA1312, SA1403, SA1649

namespace Formatters
{
	using MsgPack = global::MessagePack;

	internal sealed class ContainingClass_Derived2Formatter : MsgPack::Formatters.IMessagePackFormatter<global::ContainingClass.Derived2>
	{

		public void Serialize(ref MsgPack::MessagePackWriter writer, global::ContainingClass.Derived2 value, MsgPack::MessagePackSerializerOptions options)
		{
			if (value == null)
			{
				writer.WriteNil();
				return;
			}

			writer.WriteArrayHeader(0);
		}

		public global::ContainingClass.Derived2 Deserialize(ref MsgPack::MessagePackReader reader, MsgPack::MessagePackSerializerOptions options)
		{
			if (reader.TryReadNil())
			{
				return null;
			}

			reader.Skip();
			return new global::ContainingClass.Derived2();
		}
	}
}
