// <auto-generated />

#pragma warning disable 618, 612, 414, 168, CS1591, SA1129, SA1309, SA1312, SA1403, SA1649

namespace MessagePack.Formatters.MyTestNamespace
{
	using MsgPack = global::MessagePack;
	using MyEnum = global::MyTestNamespace.MyEnum;

	internal sealed class MyEnumFormatter : MsgPack::Formatters.IMessagePackFormatter<MyEnum>
	{
		public void Serialize(ref MsgPack::MessagePackWriter writer, MyEnum value, MsgPack::MessagePackSerializerOptions options)
		{
			writer.Write((int)value);
		}

		public MyEnum Deserialize(ref MsgPack::MessagePackReader reader, MsgPack::MessagePackSerializerOptions options)
		{
			return (MyEnum)reader.ReadInt32();
		}
	}
}
