// <auto-generated />

#pragma warning disable 618, 612, 414, 168, CS1591, SA1129, SA1309, SA1312, SA1403, SA1649

#pragma warning disable CS8669 // We may leak nullable annotations into generated code.

using MsgPack = global::MessagePack;

namespace MessagePack {
internal partial class GeneratedMessagePackResolver {

	internal sealed class GFormatter : MsgPack::Formatters.IMessagePackFormatter<global::G>
	{
		private readonly global::MessagePack.Formatters.StringInterningFormatter __aCustomFormatter__ = new global::MessagePack.Formatters.StringInterningFormatter();

		public void Serialize(ref MsgPack::MessagePackWriter writer, global::G value, MsgPack::MessagePackSerializerOptions options)
		{
			if (value == null)
			{
				writer.WriteNil();
				return;
			}

			writer.WriteArrayHeader(1);
			this.__aCustomFormatter__.Serialize(ref writer, value.a, options);
		}

		public global::G Deserialize(ref MsgPack::MessagePackReader reader, MsgPack::MessagePackSerializerOptions options)
		{
			if (reader.TryReadNil())
			{
				return null;
			}

			options.Security.DepthStep(ref reader);
			var length = reader.ReadArrayHeader();
			var ____result = new global::G();

			for (int i = 0; i < length; i++)
			{
				switch (i)
				{
					case 0:
						____result.a = this.__aCustomFormatter__.Deserialize(ref reader, options);
						break;
					default:
						reader.Skip();
						break;
				}
			}

			reader.Depth--;
			return ____result;
		}
	}
}
}
