using System.Runtime.CompilerServices;
using System.Runtime.Loader;
using MessagePack.SourceGenerator.Generators;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Xunit;

namespace MessagePack.Tests;

// Generated registrations from several assemblies land in one process-global registry.
// A declaration (type-level [MessagePackFormatter], surrogate) registered by the declaring
// assembly must outrank the incidental defaults another assembly harvests for the same type
// from its member graphs, whatever order the modules initialize in. The 2026-09-04 review
// found a consumer's harvested EnumInt32Formatter replacing a library's declared
// EnumAsStringFormatterFactory, so a value written before the consumer loaded could no
// longer be read.
public class CrossAssemblyRegistrationTests
{
    // an identity marker only: nothing is ever constructed through it, so the
    // MsgPack102 bridge note does not apply
#pragma warning disable MsgPack102
    sealed class MarkerFactory : MessagePackFormatterFactory
    {
        public override object? CreateFormatter(Type writeBufferType, Type readBufferType, Type valueType) => null;
    }
#pragma warning restore MsgPack102

    [Fact]
    public void RegisterHarvested_NeverDisplacesADeclaration_InEitherOrder()
    {
        var declared = new MarkerFactory();
        var harvested = new MarkerFactory();

        var registry = new SourceGeneratedFormatterFactory();
        registry.Register(typeof(int), declared);
        registry.RegisterHarvested(typeof(int), harvested);
        Assert.Same(declared, Registered(registry, typeof(int)));

        registry = new SourceGeneratedFormatterFactory();
        registry.RegisterHarvested(typeof(int), harvested);
        registry.Register(typeof(int), declared);
        Assert.Same(declared, Registered(registry, typeof(int)));

        // a lone harvested default still serves
        registry = new SourceGeneratedFormatterFactory();
        registry.RegisterHarvested(typeof(int), harvested);
        Assert.Same(harvested, Registered(registry, typeof(int)));
    }

    static MessagePackFormatterFactory? Registered(SourceGeneratedFormatterFactory registry, Type type)
    {
        var factories = (System.Collections.Concurrent.ConcurrentDictionary<Type, MessagePackFormatterFactory>)typeof(SourceGeneratedFormatterFactory)
            .GetField("factories", System.Reflection.BindingFlags.Instance | System.Reflection.BindingFlags.NonPublic)!
            .GetValue(registry)!;
        return factories.TryGetValue(type, out var factory) ? factory : null;
    }

    // the review's scenario end to end: a library declares an enum's formatter, a consumer
    // DTO merely uses the enum; both assemblies are generated by the actual generator
    [Fact]
    public void ConsumerHarvest_DoesNotOverrideTheLibraryDeclaredEnumFormatter()
    {
        var suffix = Guid.NewGuid().ToString("N");
        var libraryBytes = Compile("RegLibrary" + suffix, $$"""
            using MessagePack;
            using MessagePack.Formatters;
            namespace RegLibrary{{suffix}};
            [MessagePackFormatter(typeof(EnumAsStringFormatterFactory<Fruit>))]
            public enum Fruit { Banana = 7 }
            """);
        var library = AssemblyLoadContext.Default.LoadFromStream(new MemoryStream(libraryBytes));
        RuntimeHelpers.RunModuleConstructor(library.ManifestModule.ModuleHandle);
        var fruit = library.GetType($"RegLibrary{suffix}.Fruit")!;
        var banana = Enum.ToObject(fruit, 7);

        var warm = new MessagePackSerializerOptions(new MessagePackFormatterResolver(MessagePackFormatterFactory.Default));
        var written = MessagePackSerializer.Serialize(fruit, banana, warm);
        Assert.Equal("\"Banana\"", MessagePackSerializer.ConvertToJson(written));

        var consumerBytes = Compile("RegConsumer" + suffix, $$"""
            using System.Collections.Generic;
            using MessagePack;
            using RegLibrary{{suffix}};
            namespace RegConsumer{{suffix}};
            [MessagePackObject]
            public class Basket { [Key(0)] public Fruit Fruit { get; set; } = Fruit.Banana; [Key(1)] public List<Fruit> More { get; set; } = [Fruit.Banana]; }
            """, MetadataReference.CreateFromImage(libraryBytes));
        var consumer = AssemblyLoadContext.Default.LoadFromStream(new MemoryStream(consumerBytes));
        RuntimeHelpers.RunModuleConstructor(consumer.ManifestModule.ModuleHandle);

        // the consumer's module initializer ran after the library's: the declaration stands
        var fresh = new MessagePackSerializerOptions(new MessagePackFormatterResolver(MessagePackFormatterFactory.Default));
        Assert.Equal("\"Banana\"", MessagePackSerializer.ConvertToJson(MessagePackSerializer.Serialize(fruit, banana, fresh)));
        Assert.Equal(banana, MessagePackSerializer.Deserialize(fruit, written, fresh));

        // and the consumer DTO's members go through it too (List<TEnum> falls back from the
        // integer codec when the element formatter is not the built-in one)
        var basket = consumer.GetType($"RegConsumer{suffix}.Basket")!;
        Assert.Equal("[\"Banana\",[\"Banana\"]]", MessagePackSerializer.ConvertToJson(MessagePackSerializer.Serialize(basket, Activator.CreateInstance(basket), fresh)));
    }

    static byte[] Compile(string assemblyName, string source, params MetadataReference[] additionalReferences)
    {
        var parseOptions = CSharpParseOptions.Default.WithLanguageVersion(LanguageVersion.Latest).WithPreprocessorSymbols("NET10_0_OR_GREATER");
        var compilation = CSharpCompilation.Create(
            assemblyName,
            [CSharpSyntaxTree.ParseText(source, parseOptions)],
            AnalyzerTestHost.References.Concat(additionalReferences),
            new CSharpCompilationOptions(OutputKind.DynamicallyLinkedLibrary));
        var driver = CSharpGeneratorDriver.Create([new MessagePackGenerator().AsSourceGenerator()], parseOptions: parseOptions);
        driver.RunGeneratorsAndUpdateCompilation(compilation, out var updated, out var generatorDiagnostics);
        var errors = generatorDiagnostics.Concat(updated.GetDiagnostics()).Where(static d => d.Severity == DiagnosticSeverity.Error).ToArray();
        Assert.True(errors.Length == 0, string.Join("\n", errors.Select(static d => d.ToString())));

        using var stream = new MemoryStream();
        var emitted = updated.Emit(stream);
        Assert.True(emitted.Success, string.Join("\n", emitted.Diagnostics.Where(static d => d.Severity == DiagnosticSeverity.Error)));
        return stream.ToArray();
    }
}
