using MessagePack.SourceGenerator.Generators;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Xunit;

namespace MessagePack.Tests;

// Every generated file opens with a blanket `#pragma warning disable`: the consumer's warning configuration
// (SDK analyzers, TreatWarningsAsErrors, custom rule sets) must never fail a build on emitted code, and an id list
// would rot per SDK. The pragma also hides emitter mistakes, so the second test strips it and re-compiles the
// generated trees at the highest warning level with nullable warnings on: emitted code stays warning-free in this
// repo even though consumers never see a warning from it.
public class GeneratedCodeWarningTests
{
    const string Probe = """
        using System;
        using System.Collections.Generic;
        using MessagePack;

        [MessagePackObject]
        public class IntKeyed
        {
            [Key(0)] public int Id { get; set; }
            [Key(1)] public string? Name { get; set; }
            [Key(2)] public List<int>? Items { get; set; }
            [Key(3)] public Dictionary<string, IntKeyed>? Children { get; set; }
            [Key(5)] public DateTime? When { get; set; }
        }

        [MessagePackObject]
        public class StringKeyedConstructed
        {
            [Key("id")] public int Id { get; }
            [Key("name")] public string? Name { get; }
            [Key("score")] public double Score { get; init; }
            public StringKeyedConstructed(int id, string? name)
            {
                Id = id;
                Name = name;
            }
        }

        [MessagePackObject(true)]
        public class MapMode
        {
            public required string Name { get; set; }
            public int Value { get; set; }
            public int Computed => Value * 2;
        }

        [MessagePackObject(KeyNamingPolicy.SnakeCaseLower)]
        public class SnakeMap
        {
            public int FirstValue { get; set; }
            public string? SecondValue { get; set; }
        }

        // string-keyed with zero keyed members: the shape that once leaked CS0219 (an unused seenMembers ledger)
        [MessagePackObject(true)]
        public class PacketOnly
        {
            public MessagePackUnknownMembers? Unknown { get; set; }
        }

        [MessagePackObject(true)]
        public class PacketWithMembers
        {
            public int Id { get; set; }
            public MessagePackUnknownMembers? Unknown { get; set; }
        }

        [MessagePackObject]
        public struct Point
        {
            [Key(0)] public int X;
            [Key(1)] public int Y;
        }

        [MessagePackObject]
        public record Pair([property: Key(0)] int Left, [property: Key(1)] string Right);

        [MessagePackObject]
        public class Wrapper<T>
        {
            [Key(0)] public T? Value { get; set; }
            [Key(1)] public List<T>? Many { get; set; }
        }

        [UnionTag(typeof(Circle), 0)]
        [UnionTag(typeof(Rectangle), 1)]
        public abstract class Shape
        {
        }

        [MessagePackObject]
        public class Circle : Shape
        {
            [Key(0)] public double Radius { get; set; }
        }

        [MessagePackObject]
        public class Rectangle : Shape
        {
            [Key(0)] public double Width { get; set; }
            [Key(1)] public double Height { get; set; }
        }

        [MessagePackObject(AllowCircularReferences = true)]
        public class Node
        {
            [Key(0)] public Node? Parent { get; set; }
            [Key(1)] public List<Node>? Children { get; set; }
        }

        [MessagePackObject]
        public class Callbacks : IMessagePackSerializationCallbackReceiver
        {
            [Key(0)] public int Value { get; set; }
            public void OnBeforeSerialize() { }
            public void OnAfterDeserialize() { }
        }

        [MessagePackObject(AllowPrivate = true)]
        public partial class Hidden
        {
            [Key(0)] private int secret;
            [IgnoreMember] public int Secret => secret;
        }
        """;

    const string ObsoleteProbe = """
        using System;
        using MessagePack;

        [MessagePackObject]
        public class WithObsolete
        {
            [Key(0)] public int Id { get; set; }
            [Obsolete("use Id")]
            [Key(1)] public int OldId { get; set; }
        }
        """;

    [Fact]
    public void EveryGeneratedFile_OpensWithTheBlanketPragma()
    {
        var (_, generated) = RunGenerator(Probe);
        Assert.NotEmpty(generated);
        foreach (var tree in generated)
        {
            var text = tree.ToString();
            Assert.StartsWith("// <auto-generated/>\n#pragma warning disable\n", text, StringComparison.Ordinal);
        }
    }

    [Fact]
    public void GeneratedCode_IsWarningFreeWithoutThePragma()
    {
        var (compilation, generated) = RunGenerator(Probe);
        var warnings = GeneratedWarningsWithoutPragma(compilation, generated);
        Assert.True(warnings.Count == 0, string.Join(Environment.NewLine, warnings));
    }

    // an [Obsolete] member is the one warning generated code legitimately triggers (it must read and write the
    // member): the consumer never sees it, and the stripped compilation proves the harness above does see warnings
    [Fact]
    public void ObsoleteMember_WarnsOnlyWithThePragmaStripped()
    {
        var (compilation, generated) = RunGenerator(ObsoleteProbe);

        var asEmitted = compilation.GetDiagnostics()
            .Where(d => d.Severity == DiagnosticSeverity.Warning && d.Location.SourceTree is { } tree && generated.Contains(tree))
            .ToList();
        Assert.Empty(asEmitted);

        var stripped = GeneratedWarningsWithoutPragma(compilation, generated);
        Assert.NotEmpty(stripped);
        Assert.All(stripped, d => Assert.Equal("CS0618", d.Id));
    }

    static (Compilation Compilation, List<SyntaxTree> Generated) RunGenerator(string source)
    {
        var compilation = AnalyzerTestHost.CreateCompilation(source, "WarningProbe" + Guid.NewGuid().ToString("N"));
        var parseOptions = (CSharpParseOptions)compilation.SyntaxTrees.First().Options;
        var driver = CSharpGeneratorDriver.Create([new MessagePackGenerator().AsSourceGenerator()], parseOptions: parseOptions);
        var result = driver.RunGeneratorsAndUpdateCompilation(compilation, out var updated, out var generatorDiagnostics, CancellationToken.None).GetRunResult();
        Assert.Empty(generatorDiagnostics.Where(static d => d.Severity == DiagnosticSeverity.Error));
        Assert.Empty(updated.GetDiagnostics().Where(static d => d.Severity == DiagnosticSeverity.Error));
        return (updated, [.. result.GeneratedTrees]);
    }

    // the generated trees with their leading pragma removed, compiled at the widest warning surface; only
    // diagnostics located in generated code count (the probe source itself is not under test)
    static List<Diagnostic> GeneratedWarningsWithoutPragma(Compilation compilation, List<SyntaxTree> generated)
    {
        var stripped = new List<SyntaxTree>(generated.Count);
        foreach (var tree in generated)
        {
            var text = tree.ToString();
            const string Pragma = "#pragma warning disable\n";
            var index = text.IndexOf(Pragma, StringComparison.Ordinal);
            Assert.True(index >= 0, "generated file without the blanket pragma: " + tree.FilePath);
            var withoutPragma = CSharpSyntaxTree.ParseText(text.Remove(index, Pragma.Length), (CSharpParseOptions)tree.Options, tree.FilePath);
            compilation = compilation.ReplaceSyntaxTree(tree, withoutPragma);
            stripped.Add(withoutPragma);
        }
        var options = ((CSharpCompilationOptions)compilation.Options)
            .WithWarningLevel(9999)
            .WithNullableContextOptions(NullableContextOptions.Enable);
        return compilation.WithOptions(options).GetDiagnostics()
            .Where(d => d.Severity == DiagnosticSeverity.Warning && d.Location.SourceTree is { } tree && stripped.Contains(tree))
            .ToList();
    }
}
