// <auto-generated />

#pragma warning disable 618, 612, 414, 168, CS1591, SA1129, SA1309, SA1312, SA1403, SA1649

#pragma warning disable CS8669 // We may leak nullable annotations into generated code.

using MsgPack = global::MessagePack;

namespace A {
internal partial class MyObject {

	internal sealed class MyObjectFormatter : MsgPack::Formatters.IMessagePackFormatter<global::A.MyObject>
	{

		public void Serialize(ref MsgPack::MessagePackWriter writer, global::A.MyObject value, MsgPack::MessagePackSerializerOptions options)
		{
			if (value == null)
			{
				writer.WriteNil();
				return;
			}

			writer.WriteArrayHeader(1);
			writer.Write(value.value);
		}

		public global::A.MyObject Deserialize(ref MsgPack::MessagePackReader reader, MsgPack::MessagePackSerializerOptions options)
		{
			if (reader.TryReadNil())
			{
				return null;
			}

			options.Security.DepthStep(ref reader);
			var length = reader.ReadArrayHeader();
			var ____result = new global::A.MyObject();

			for (int i = 0; i < length; i++)
			{
				switch (i)
				{
					case 0:
						____result.value = reader.ReadInt32();
						break;
					default:
						reader.Skip();
						break;
				}
			}

			reader.Depth--;
			return ____result;
		}
	}
}
}
