using Microsoft.CodeAnalysis;
using System.Collections.Immutable;
using System.Text;

namespace UltraMessagePack.SourceGenerator;

/// <summary>
/// Emits one formatter class per [MessagePackObject] type plus a factory + module
/// initializer. Output shape follows the measured house style:
///   Serialize   - direct-writable members (and headers/keys) are batched into shared
///                 reservations: one GetReference over the summed worst-case sizes, a
///                 register-resident offset, one Advance per run (DisasmProbe9: -11..16%
///                 vs per-value calls). A member without a direct writer flushes the run
///                 and dispatches through its formatter field.
///   Deserialize - per-value loop+switch (int keys) or utf8 in-place key match (string
///                 keys); unknown keys/extra array slots are skipped for version
///                 tolerance. Measured equal to straight-line reads (the decode chain
///                 dominates), and it handles count mismatches naturally.
///   Nested      - formatters resolved once in Initialize into interface fields
///                 (DisasmProbe11: per-call resolution is strictly worse).
/// </summary>
static class Emitter
{
    public static string EmitFormatter(ObjectModel model)
    {
        var builder = new StringBuilder();
        var valueType = model.IsValueType ? model.FullTypeName : model.FullTypeName + "?";

        builder.Append($$"""
            // <auto-generated/>
            #nullable enable annotations
            using SerializerFoundation;
            using System.Runtime.CompilerServices;
            using UltraMessagePack;
            using static UltraMessagePack.MessagePackPrimitives;

            namespace UltraMessagePack.Generated
            {
                internal sealed class {{model.FormatterName}}<TWriteBuffer, TReadBuffer> : IMessagePackFormatter<TWriteBuffer, TReadBuffer, {{valueType}}>
                    where TWriteBuffer : struct, IWriteBuffer, allows ref struct
                    where TReadBuffer : struct, IReadBuffer, allows ref struct
                {

            """);

        foreach (var member in model.Members)
        {
            if (member.Direct == DirectKind.None)
            {
                builder.Append($"        IMessagePackFormatter<TWriteBuffer, TReadBuffer, {member.TypeName}> f{member.Name} = null!;\n");
            }
        }

        builder.Append("\n        public void Initialize(MessagePackFormatterResolver resolver)\n        {\n");
        foreach (var member in model.Members)
        {
            if (member.Direct == DirectKind.None)
            {
                builder.Append($"            f{member.Name} = resolver.GetFormatter<TWriteBuffer, TReadBuffer, {member.TypeName}>();\n");
            }
        }
        builder.Append("        }\n\n");

        EmitSerialize(builder, model, valueType);
        builder.Append('\n');
        EmitDeserialize(builder, model, valueType);

        builder.Append("""
                }
            }

            """);
        return builder.ToString();
    }

    static void EmitSerialize(StringBuilder builder, ObjectModel model, string valueType)
    {
        builder.Append($"        public void Serialize(ref TWriteBuffer buffer, ref SerializeState state, ref {valueType} value)\n        {{\n");
        if (!model.IsValueType)
        {
            builder.Append("""
                            if (value == null)
                            {
                                buffer.WriteNil();
                                return;
                            }

                """);
        }

        // batched write runs: consecutive direct-writable items share one reservation
        var sizes = new List<string>();
        var writes = new List<string>();

        void Direct(string sizeExpression, string writeCall)
        {
            sizes.Add(sizeExpression);
            writes.Add(writeCall);
        }

        void Flush()
        {
            if (writes.Count == 0)
            {
                return;
            }
            if (writes.Count == 1)
            {
                // a lone item needs no offset chain
                builder.Append($"            buffer.Advance({writes[0].Replace("{DEST}", $"ref buffer.GetReference({sizes[0]})")});\n");
            }
            else
            {
                builder.Append("            {\n");
                builder.Append($"                ref var d = ref buffer.GetReference({string.Join(" + ", sizes)});\n");
                builder.Append("                var w = 0;\n");
                foreach (var write in writes)
                {
                    builder.Append($"                w += {write.Replace("{DEST}", "ref Unsafe.Add(ref d, w)")};\n");
                }
                builder.Append("                buffer.Advance(w);\n            }\n");
            }
            sizes.Clear();
            writes.Clear();
        }

        if (!model.IsStringKey)
        {
            var count = model.MaxIntKey + 1;
            Direct(
                count <= 15 ? "1" : "MaxArrayHeaderLength",
                count <= 15 ? $"UnsafeWriteFixArrayHeader({{DEST}}, {count})" : $"UnsafeWriteArrayHeader({{DEST}}, {count})");

            var byKey = model.Members.AsArray().ToDictionary(static m => m.IntKey);
            for (int key = 0; key <= model.MaxIntKey; key++)
            {
                if (byKey.TryGetValue(key, out var member))
                {
                    EmitValueWrite(builder, member, Direct, Flush);
                }
                else
                {
                    Direct("1", "UnsafeWriteNil({DEST})"); // key hole
                }
            }
        }
        else
        {
            var count = model.Members.Length;
            Direct(
                count <= 15 ? "1" : "MaxMapHeaderLength",
                count <= 15 ? $"UnsafeWriteFixMapHeader({{DEST}}, {count})" : $"UnsafeWriteMapHeader({{DEST}}, {count})");

            foreach (var member in model.Members)
            {
                var keyLiteral = Escape(member.StringKey);
                Direct(
                    (Encoding.UTF8.GetByteCount(member.StringKey) + 5).ToString(),
                    $"UnsafeWriteString({{DEST}}, \"{keyLiteral}\"u8)");
                EmitValueWrite(builder, member, Direct, Flush);
            }
        }

        Flush();
        builder.Append("        }\n");
    }

    static void EmitValueWrite(StringBuilder builder, MemberModel member, Action<string, string> direct, Action flush)
    {
        if (member.Direct == DirectKind.None)
        {
            flush();
            builder.Append($"            var v{member.Name} = value.{member.Name};\n");
            builder.Append($"            f{member.Name}.Serialize(ref buffer, ref state, ref v{member.Name});\n");
            return;
        }

        var access = $"value.{member.Name}";
        var (writer, size) = member.Direct switch
        {
            DirectKind.Int32 => ("UnsafeWriteInt32", "MaxInt32Length"),
            DirectKind.UInt32 => ("UnsafeWriteUInt32", "MaxUInt32Length"),
            DirectKind.Int64 => ("UnsafeWriteInt64", "MaxInt64Length"),
            DirectKind.UInt64 => ("UnsafeWriteUInt64", "MaxUInt64Length"),
            DirectKind.Int16 => ("UnsafeWriteInt16", "MaxInt16Length"),
            DirectKind.UInt16 => ("UnsafeWriteUInt16", "MaxUInt16Length"),
            DirectKind.Byte => ("UnsafeWriteByte", "MaxUInt8Length"),
            DirectKind.SByte => ("UnsafeWriteSByte", "MaxInt8Length"),
            DirectKind.Boolean => ("UnsafeWriteBoolean", "1"),
            DirectKind.Char => ("UnsafeWriteChar", "MaxUInt16Length"),
            DirectKind.Single => ("UnsafeWriteSingle", "MaxFloat32Length"),
            DirectKind.Double => ("UnsafeWriteDouble", "MaxFloat64Length"),
            DirectKind.String => ("UnsafeWriteString", $"GetMaxStringByteCount({access})"),
            DirectKind.DateTime => ("UnsafeWriteTimestamp", "MaxTimestampLength"),
            _ => throw new InvalidOperationException(),
        };
        direct(size, $"{writer}({{DEST}}, {access})");
    }

    static void EmitDeserialize(StringBuilder builder, ObjectModel model, string valueType)
    {
        builder.Append($"        public void Deserialize(ref TReadBuffer buffer, ref DeserializeState state, ref {valueType} value)\n        {{\n");
        if (model.IsValueType)
        {
            builder.Append($$"""
                            if (buffer.TryReadNil())
                            {
                                throw new MessagePackSerializationException("code Nil cannot deserialize into the non-nullable struct '{{model.FullTypeName}}'.");
                            }
                            var result = value;

                """);
        }
        else
        {
            builder.Append($$"""
                            if (buffer.TryReadNil())
                            {
                                value = null;
                                return;
                            }
                            var result = value ?? new {{model.FullTypeName}}();

                """);
        }

        if (!model.IsStringKey)
        {
            builder.Append("""
                            var count = buffer.ReadArrayHeader();
                            for (int i = 0; i < count; i++)
                            {
                                switch (i)
                                {

                """);
            foreach (var member in model.Members)
            {
                builder.Append($"                    case {member.IntKey}:\n");
                EmitValueRead(builder, member, "                        ");
                builder.Append("                        break;\n");
            }
            builder.Append("""
                                    default:
                                        buffer.Skip(); // version tolerance: unknown trailing member
                                        break;
                                }
                            }

                """);
        }
        else
        {
            builder.Append("""
                            var count = buffer.ReadMapHeader();
                            for (int i = 0; i < count; i++)
                            {
                                // compare the key as utf8 in place, BEFORE Advance: the span may
                                // alias a pooled stitch buffer
                                var byteCount = buffer.ReadStringHeader();
                                var key = buffer.GetSpan(byteCount);
                                if (key.Length < byteCount)
                                {
                                    throw new MessagePackSerializationException("Unexpected end of data while reading a map key.");
                                }
                                key = key.Slice(0, byteCount);

                """);
            var first = true;
            foreach (var member in model.Members)
            {
                var keyword = first ? "if" : "else if";
                first = false;
                builder.Append($"                {keyword} (key.SequenceEqual(\"{Escape(member.StringKey)}\"u8))\n                {{\n                    buffer.Advance(byteCount);\n");
                EmitValueRead(builder, member, "                    ");
                builder.Append("                }\n");
            }
            builder.Append("""
                                else
                                {
                                    buffer.Advance(byteCount);
                                    buffer.Skip(); // version tolerance: unknown key's value
                                }
                            }

                """);
        }

        builder.Append("            value = result;\n        }\n");
    }

    static void EmitValueRead(StringBuilder builder, MemberModel member, string indent)
    {
        if (member.Direct == DirectKind.None)
        {
            builder.Append($"{indent}{{\n");
            builder.Append($"{indent}    var v = result.{member.Name};\n");
            builder.Append($"{indent}    f{member.Name}.Deserialize(ref buffer, ref state, ref v);\n");
            builder.Append($"{indent}    result.{member.Name} = v;\n");
            builder.Append($"{indent}}}\n");
            return;
        }

        var reader = member.Direct switch
        {
            DirectKind.Int32 => "ReadInt32",
            DirectKind.UInt32 => "ReadUInt32",
            DirectKind.Int64 => "ReadInt64",
            DirectKind.UInt64 => "ReadUInt64",
            DirectKind.Int16 => "ReadInt16",
            DirectKind.UInt16 => "ReadUInt16",
            DirectKind.Byte => "ReadByte",
            DirectKind.SByte => "ReadSByte",
            DirectKind.Boolean => "ReadBoolean",
            DirectKind.Char => "ReadChar",
            DirectKind.Single => "ReadSingle",
            DirectKind.Double => "ReadDouble",
            DirectKind.String => "ReadString",
            DirectKind.DateTime => "ReadTimestamp",
            _ => throw new InvalidOperationException(),
        };
        builder.Append($"{indent}result.{member.Name} = buffer.{reader}();\n");
    }

    public static string EmitFactory(ImmutableArray<ObjectModel?> models)
    {
        var ordered = models
            .Where(static m => m is not null)
            .Select(static m => m!)
            .OrderBy(static m => m.FullTypeName, StringComparer.Ordinal)
            .ToArray();

        var builder = new StringBuilder();
        builder.Append("""
            // <auto-generated/>
            #nullable enable annotations
            using SerializerFoundation;
            using UltraMessagePack;

            namespace UltraMessagePack.Generated
            {
                internal sealed class GeneratedMessagePackFormatterFactory : IMessagePackFormatterFactory
                {
                    public static readonly GeneratedMessagePackFormatterFactory Instance = new GeneratedMessagePackFormatterFactory();

                    GeneratedMessagePackFormatterFactory()
                    {
                    }

                    public object? CreateFormatter<TWriteBuffer, TReadBuffer>(global::System.Type type)
                        where TWriteBuffer : struct, IWriteBuffer, allows ref struct
                        where TReadBuffer : struct, IReadBuffer, allows ref struct
                    {

            """);
        foreach (var model in ordered)
        {
            builder.Append($"            if (type == typeof({model.FullTypeName})) return new {model.FormatterName}<TWriteBuffer, TReadBuffer>();\n");
        }
        builder.Append("""
                        return null;
                    }
                }

                internal static class GeneratedMessagePackRegistration
                {
                    // MessagePackSerializer.Default resolves through DynamicFormatterFactory, so
                    // generated types work without manual registration; an explicit chain can
                    // still place GeneratedMessagePackFormatterFactory.Instance directly.
                    [global::System.Runtime.CompilerServices.ModuleInitializer]
                    internal static void Register()
                    {

            """);
        foreach (var model in ordered)
        {
            builder.Append($"            DynamicFormatterFactory.Instance.Register(typeof({model.FullTypeName}), GeneratedMessagePackFormatterFactory.Instance);\n");
        }
        builder.Append("""
                    }
                }
            }

            """);
        return builder.ToString();
    }

    static string Escape(string value)
    {
        var builder = new StringBuilder(value.Length);
        foreach (var c in value)
        {
            switch (c)
            {
                case '"': builder.Append("\\\""); break;
                case '\\': builder.Append("\\\\"); break;
                case '\n': builder.Append("\\n"); break;
                case '\r': builder.Append("\\r"); break;
                case '\t': builder.Append("\\t"); break;
                case '\0': builder.Append("\\0"); break;
                default: builder.Append(c); break;
            }
        }
        return builder.ToString();
    }
}
