//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MessagePackAnalyzer {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MessagePackAnalyzer.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   すべてについて、現在のスレッドの CurrentUICulture プロパティをオーバーライドします
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Without an explicit MessagePackSerializerOptions argument, a shared/static default will be assumed which any other code in the entire AppDomain or process can alter, causing malfunction in your invocation. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MsgPack001_Description {
            get {
                return ResourceManager.GetString("MsgPack001_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Supply a value for the MessagePackSerializerOptions argument に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MsgPack001_MessageFormat {
            get {
                return ResourceManager.GetString("MsgPack001_MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Avoid mutable default options に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MsgPack001_Title {
            get {
                return ResourceManager.GetString("MsgPack001_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Providing a static value for MessagePackSerializerOptions from a mutable member can lead to malfunction when that member is mutated by another party. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MsgPack002_Description {
            get {
                return ResourceManager.GetString("MsgPack002_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Avoid using a mutable static value for MessagePackSerializerOptions に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MsgPack002_MessageFormat {
            get {
                return ResourceManager.GetString("MsgPack002_MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Avoid mutable static options に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MsgPack002_Title {
            get {
                return ResourceManager.GetString("MsgPack002_Title", resourceCulture);
            }
        }
    }
}
