// <auto-generated />

#pragma warning disable 618, 612, 414, 168, CS1591, SA1129, SA1309, SA1312, SA1403, SA1649

using MsgPack = global::MessagePack;

namespace MessagePack {
partial class GeneratedMessagePackResolver {
internal partial class NS1 {

	internal sealed class MyEnumFormatter : MsgPack::Formatters.IMessagePackFormatter<global::NS1.MyEnum>
	{
		public void Serialize(ref MsgPack::MessagePackWriter writer, global::NS1.MyEnum value, MsgPack::MessagePackSerializerOptions options)
		{
			writer.Write((int)value);
		}

		public global::NS1.MyEnum Deserialize(ref MsgPack::MessagePackReader reader, MsgPack::MessagePackSerializerOptions options)
		{
			return (global::NS1.MyEnum)reader.ReadInt32();
		}
	}

}
}
}
