// <auto-generated />

#pragma warning disable 618, 612, 414, 168, CS1591, SA1129, SA1309, SA1312, SA1403, SA1649

#pragma warning disable CS8669 // We may leak nullable annotations into generated code.

using MsgPack = global::MessagePack;

namespace MessagePack {
internal partial class GeneratedMessagePackResolver {
internal partial class A {

	internal sealed class BFormatter : MsgPack::Formatters.IMessagePackFormatter<global::A.B>
	{

		public void Serialize(ref MsgPack::MessagePackWriter writer, global::A.B value, MsgPack::MessagePackSerializerOptions options)
		{
			if (value == null)
			{
				writer.WriteNil();
				return;
			}

			writer.WriteArrayHeader(1);
			MsgPack::FormatterResolverExtensions.SerializeWithVerifyByValue<global::A.B.C[]>(ref writer, value.array, options);
		}

		public global::A.B Deserialize(ref MsgPack::MessagePackReader reader, MsgPack::MessagePackSerializerOptions options)
		{
			if (reader.TryReadNil())
			{
				return null;
			}

			options.Security.DepthStep(ref reader);
			var length = reader.ReadArrayHeader();
			var ____result = new global::A.B();

			for (int i = 0; i < length; i++)
			{
				switch (i)
				{
					case 0:
						____result.array = MsgPack::FormatterResolverExtensions.DeserializeWithVerifyByValue<global::A.B.C[]>(ref reader, options);
						break;
					default:
						reader.Skip();
						break;
				}
			}

			reader.Depth--;
			return ____result;
		}
	}
}
}
}
