using System.Buffers;
using CsCheck;
using MessagePack;
using Xunit;

namespace MessagePack.Tests.Robustness;

// Property-based robustness tests for the deserialization security contract (see
// RobustnessHarness). Every generated byte sequence must terminate and, if it fails, fail
// ONLY through the sanctioned exception set - never a raw framework exception, OOM, or hang.
//
// Built on CsCheck (property-based generation with automatic shrinking): when a generated
// input breaks the contract, CsCheck shrinks it to a MINIMAL counterexample and prints a
// seed string that reproduces it exactly (`CsCheck_Seed=...`). That is the upgrade over the
// former hand-rolled random loops - a failure now arrives pre-minimized instead of as a raw
// blob to hand-trim (which is what the LZ4 allocation-bomb finding needed). The coverage-
// guided escalation still lives in MessagePack.Tests.Fuzz (SharpFuzz/libFuzzer), sharing the
// same targets, seeds, and IsSanctioned oracle via RobustnessTargets by compile-link.
//
// Generation is fresh each run (CsCheck's default), so coverage accumulates across runs
// instead of retesting one fixed set; any red is a real contract break (the oracle is
// exact, so there are no false positives), reproducible from the printed seed. Set
// ROBUSTNESS_SECONDS to trade the bounded per-strategy iteration count for a wall-clock soak
// budget; set CsCheck_Seed to pin a run deterministically.
public class RobustnessTests
{
    // (target type x resolver tier) thunks and the valid-payload seeds live in
    // RobustnessTargets, shared with the SharpFuzz harness.
    static readonly (string Name, Action<byte[]> Deserialize)[] Targets = RobustnessTargets.Targets;
    static readonly byte[][] Corpus = RobustnessTargets.SeedCorpus();

    // Per-strategy iteration count for a normal (non-soak) run. Each iteration drives the
    // input through all Targets under the hang guard, so the real attempt count is
    // Iterations x Targets.Length. Kept modest so the suite stays CI-fast.
    const int DefaultIter = 200;

    // ---- strategy 1: uniformly random bytes ----
    [Fact]
    public void RandomBytes()
        => Check(Gen.Byte.Array[0, 256]);

    // ---- strategy 2: bit/byte mutation of a valid payload ----
    [Fact]
    public void MutatedValidPayloads()
    {
        // pick a seed, then apply 1..7 mutations; CsCheck shrinks the mutation set and the
        // per-mutation values, so a surviving counterexample is the fewest/smallest edits
        // to a valid payload that break the contract.
        var gen =
            from ci in Gen.Int[0, Corpus.Length - 1]
            from muts in Gen.Select(Gen.Int[0, Math.Max(0, Corpus[ci].Length - 1)], Gen.Int[0, 2], Gen.Byte)
                .Array[1, 7]
            select ApplyMutations(Corpus[ci], muts);
        Check(gen);
    }

    // ---- strategy 3: truncation (an arbitrary prefix of a valid payload) ----
    [Fact]
    public void TruncatedValidPayloads()
    {
        var gen =
            from ci in Gen.Int[0, Corpus.Length - 1]
            from len in Gen.Int[0, Corpus[ci].Length]
            select Corpus[ci][..len];
        Check(gen);
    }

    // ---- strategy 4: structured random (valid msgpack tokens, arbitrary structure) ----
    [Fact]
    public void StructuredRandomTokens()
        => Check(StructuredMessageGen);

    // ---- strategy 5: header-count/length field extremes on containers ----
    [Fact]
    public void ContainerHeaderExtremes()
    {
        // array/map/str/bin/ext headers claiming huge counts with little/no payload: the
        // allocation-bomb and implausible-header guards must reject these.
        byte[][] headers =
        [
            [0xdd, 0x7f, 0xff, 0xff, 0xff],       // array32 claiming ~2.1B
            [0xdf, 0x7f, 0xff, 0xff, 0xff],       // map32 claiming ~2.1B
            [0xdb, 0x7f, 0xff, 0xff, 0xff],       // str32 claiming ~2.1B
            [0xc6, 0x7f, 0xff, 0xff, 0xff],       // bin32 claiming ~2.1B
            [0xc9, 0x7f, 0xff, 0xff, 0xff, 0x01], // ext32 claiming ~2.1B
            [0xde, 0xff, 0xff],                   // map16 claiming 65535
            [0xdc, 0xff, 0xff],                   // array16 claiming 65535
        ];
        var gen =
            from hi in Gen.Int[0, headers.Length - 1]
            from trailer in Gen.Byte.Array[0, 16]
            select Concat(headers[hi], trailer);
        Check(gen);
    }

    // ---- structured token generator (strategy 4 support) ----

    // one leaf msgpack value rendered to bytes. Declared before StructuredGen because static
    // field initializers run in textual order and Gen.Frequency reads LeafGen eagerly.
    static readonly Gen<byte[]> LeafGen = Gen.OneOf(
        Gen.Const(Render((ref BufferWriterWriteBuffer b) => b.WriteNil())),
        Gen.Bool.Select(x => Render((ref BufferWriterWriteBuffer b) => b.WriteBoolean(x))),
        Gen.Long.Select(x => Render((ref BufferWriterWriteBuffer b) => b.WriteInt64(x))),
        Gen.ULong.Select(x => Render((ref BufferWriterWriteBuffer b) => b.WriteUInt64(x))),
        Gen.Double.Select(x => Render((ref BufferWriterWriteBuffer b) => b.WriteDouble(x))),
        Gen.Float.Select(x => Render((ref BufferWriterWriteBuffer b) => b.WriteSingle(x))),
        Gen.String[Gen.Char[(char)32, (char)126], 0, 32].Select(s => Render((ref BufferWriterWriteBuffer b) => b.WriteString(s))),
        Gen.Byte.Array[0, 32].Select(bin => Render((ref BufferWriterWriteBuffer b) => b.WriteBinary(bin))),
        Gen.SByte.Select(t => Render((ref BufferWriterWriteBuffer b) => b.WriteExtHeader(t, 0))));

    // one msgpack value rendered to bytes, recursively: leaves at any depth, arrays/maps up
    // to depth 4, plus a "lying" array header that claims more elements than follow.
    static readonly Gen<byte[]> StructuredGen = Gen.Recursive<byte[]>((depth, self) =>
        depth >= 4 ? LeafGen : Gen.Frequency(
            (12, LeafGen),
            (3, from n in Gen.Int[0, 5]
                from children in self.Array[n]
                select Concat(Render((ref BufferWriterWriteBuffer b) => b.WriteArrayHeader(n)), children)),
            (3, from n in Gen.Int[0, 4]
                from kv in self.Array[2 * n]
                select Concat(Render((ref BufferWriterWriteBuffer b) => b.WriteMapHeader(n)), kv)),
            (1, from n in Gen.Int[1, 99]
                select Render((ref BufferWriterWriteBuffer b) => b.WriteArrayHeader(n)))));

    // a full message: 1..20 top-level tokens concatenated (trailing tokens exercise
    // robustness to trailing garbage after the first value).
    static readonly Gen<byte[]> StructuredMessageGen =
        from n in Gen.Int[1, 20]
        from toks in StructuredGen.Array[n]
        select Concat(toks);

    // ---- driver ----

    // A delegate over the ref-struct write buffer (a lambda can't close over a ref struct,
    // but a ref parameter is fine, so each token renders through this).
    delegate void WriteToken(ref BufferWriterWriteBuffer buffer);

    static byte[] Render(WriteToken write)
    {
        var writer = new ArrayBufferWriter<byte>(16);
        var buffer = new BufferWriterWriteBuffer(writer);
        write(ref buffer);
        buffer.Flush();
        return writer.WrittenSpan.ToArray();
    }

    static byte[] ApplyMutations(byte[] seed, (int Pos, int Kind, byte Val)[] muts)
    {
        var copy = (byte[])seed.Clone();
        if (copy.Length == 0)
        {
            return copy;
        }
        foreach (var (pos, kind, val) in muts)
        {
            var p = pos % copy.Length;
            copy[p] = kind switch
            {
                0 => val,                                    // random byte
                1 => (byte)(copy[p] ^ (1 << (val & 7))),     // flip one bit
                _ => (val & 1) == 0 ? (byte)0xff : (byte)0x00, // extreme
            };
        }
        return copy;
    }

    static byte[] Concat(byte[] head, byte[][] tail)
    {
        var total = head.Length;
        foreach (var t in tail)
        {
            total += t.Length;
        }
        var result = new byte[total];
        head.CopyTo(result, 0);
        var offset = head.Length;
        foreach (var t in tail)
        {
            t.CopyTo(result, offset);
            offset += t.Length;
        }
        return result;
    }

    static byte[] Concat(byte[] head, byte[] tail)
    {
        var result = new byte[head.Length + tail.Length];
        head.CopyTo(result, 0);
        tail.CopyTo(result, head.Length);
        return result;
    }

    static byte[] Concat(byte[][] parts) => Concat([], parts);

    // Run one generated input through every target under the hang guard. Throws a
    // descriptive exception on the first contract break so CsCheck shrinks toward it; the
    // final (minimal) counterexample's message names the offending target and shows the
    // bytes. The ROBUSTNESS_SECONDS soak knob maps to CsCheck's wall-clock time budget.
    static void Check(Gen<byte[]> gen)
    {
        var soak = Environment.GetEnvironmentVariable("ROBUSTNESS_SECONDS");
        if (int.TryParse(soak, out var seconds) && seconds > 0)
        {
            gen.Sample(AssertContract, time: seconds);
        }
        else
        {
            gen.Sample(AssertContract, iter: DefaultIter);
        }
    }

    static bool AssertContract(byte[] bytes)
    {
        foreach (var (name, deserialize) in Targets)
        {
            var violation = RobustnessHarness.RunAttempt(
                $"{name} {RobustnessHarness.Hex(bytes)}",
                () => deserialize(bytes));
            if (violation != null)
            {
                throw new ContractViolationException(violation);
            }
        }
        return true;
    }

    sealed class ContractViolationException(string message) : Exception(message);
}
