// <auto-generated />

#pragma warning disable 618, 612, 414, 168, CS1591, SA1129, SA1309, SA1312, SA1403, SA1649

using MsgPack = global::MessagePack;

[assembly: MsgPack::Internal.GeneratedAssemblyMessagePackResolverAttribute(typeof(MessagePack.GeneratedMessagePackResolver), 3, 0)]

namespace MessagePack {

/// <summary>A MessagePack resolver that uses generated formatters for types in this assembly.</summary>
partial class GeneratedMessagePackResolver : MsgPack::IFormatterResolver
{
	/// <summary>An instance of this resolver that only returns formatters specifically generated for types in this assembly.</summary>
	public static readonly MsgPack::IFormatterResolver Instance = new GeneratedMessagePackResolver();

	private GeneratedMessagePackResolver()
	{
	}

	public MsgPack::Formatters.IMessagePackFormatter<T> GetFormatter<T>()
	{
		return FormatterCache<T>.Formatter;
	}

	private static class FormatterCache<T>
	{
		internal static readonly MsgPack::Formatters.IMessagePackFormatter<T> Formatter;

		static FormatterCache()
		{
			var f = GeneratedMessagePackResolverGetFormatterHelper.GetFormatter(typeof(T));
			if (f != null)
			{
				Formatter = (MsgPack::Formatters.IMessagePackFormatter<T>)f;
			}
		}
	}

	private static class GeneratedMessagePackResolverGetFormatterHelper
	{
		private static readonly global::System.Collections.Generic.Dictionary<global::System.Type, int> closedTypeLookup = new global::System.Collections.Generic.Dictionary<global::System.Type, int>(5)
		{
			{ typeof(global::SubObject[]), 0 },
			{ typeof(global::System.Collections.Generic.List<global::SubObject>[]), 1 },
			{ typeof(global::System.Collections.Generic.List<global::SubObject>), 2 },
			{ typeof(global::ContainerObject), 3 },
			{ typeof(global::SubObject), 4 },
		};

		internal static object GetFormatter(global::System.Type t)
		{
			if (closedTypeLookup.TryGetValue(t, out int closedKey))
			{
				switch (closedKey)
				{
					case 0: return new MsgPack::Formatters.ArrayFormatter<global::SubObject>();
					case 1: return new MsgPack::Formatters.ArrayFormatter<global::System.Collections.Generic.List<global::SubObject>>();
					case 2: return new MsgPack::Formatters.ListFormatter<global::SubObject>();
					case 3: return new global::MessagePack.GeneratedMessagePackResolver.ContainerObjectFormatter();
					case 4: return new global::MessagePack.GeneratedMessagePackResolver.SubObjectFormatter();
					default: return null; // unreachable
				};
			}

			return null;
		}
	}
}

}
