//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sandbox.Shared.GeneratedSerializers {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("MsgPack.Serialization.CodeDomSerializers.CodeDomSerializerBuilder", "0.9.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public class System_Nullable_1_Sex_Serializer : MsgPack.Serialization.MessagePackSerializer<System.Nullable<Sex>> {
        
        private MsgPack.Serialization.MessagePackSerializer<Sex> _serializer0;
        
        public System_Nullable_1_Sex_Serializer(MsgPack.Serialization.SerializationContext context) : 
                base(context) {
            this._serializer0 = context.GetSerializer<Sex>(MsgPack.Serialization.EnumMessagePackSerializerHelpers.DetermineEnumSerializationMethod(context, typeof(Sex), MsgPack.Serialization.EnumMemberSerializationMethod.Default));
        }
        
        protected override void PackToCore(MsgPack.Packer packer, System.Nullable<Sex> objectTree) {
            this._serializer0.PackTo(packer, objectTree.Value);
        }
        
        protected override System.Nullable<Sex> UnpackFromCore(MsgPack.Unpacker unpacker) {
            return new System.Nullable<Sex>(this._serializer0.UnpackFrom(unpacker));
        }
    }
}
