// <auto-generated />

#pragma warning disable 618, 612, 414, 168, CS1591, SA1129, SA1309, SA1312, SA1403, SA1649

using MsgPack = global::MessagePack;

namespace MessagePack {
internal partial class GeneratedMessagePackResolver {
internal partial class TempProject {

	internal sealed class MyEnumFormatter : MsgPack::Formatters.IMessagePackFormatter<global::TempProject.MyEnum>
	{
		public void Serialize(ref MsgPack::MessagePackWriter writer, global::TempProject.MyEnum value, MsgPack::MessagePackSerializerOptions options)
		{
			writer.Write((int)value);
		}

		public global::TempProject.MyEnum Deserialize(ref MsgPack::MessagePackReader reader, MsgPack::MessagePackSerializerOptions options)
		{
			return (global::TempProject.MyEnum)reader.ReadInt32();
		}
	}

}
}
}
