using BenchmarkDotNet.Attributes;
using System.Runtime.CompilerServices;
using SerializerFoundation;
using UltraMessagePack;
using static UltraMessagePack.MessagePackPrimitives;

// A/B: is the source-generated NbPocoAsArrayFormatter slower than the deleted
// hand-written one? Same process, same buffer, both paths resolve a formatter and hit the
// same UnsafeWrite* ladder — the only code difference is the generated null check.
// Motivated by SerializeAsArray_Ultra reading 12.67ns where memory said ~8ns; the old
// logs show the HANDWRITTEN version itself ranged 7.9–14.2ns across runs (step1 11.97 /
// step2 10.00 / step3 7.88 / ultra 14.21), so the hypothesis was run-to-run layout noise,
// not a generator regression.
//
// MEASURED (i7-13700KF, ShortRun, ns/op):
//   run1: Generated 12.23 | Handwritten 11.94  (gen +2%)
//   run2: Generated 11.78 | Handwritten 12.02  (gen -2%)
//   run3: Generated 12.19 | Handwritten 12.37 | StaticCached 11.86
// VERDICT: no generator regression (gen==hand, sign flips between runs), and the
// follow-up hypothesis "losing the static DefaultCache entry cost ~2ns" is also out:
// the resurrected frozen static readonly cache entry (SerializeStaticCached) beats the
// resolver-table entry by only ~0.3ns — confirming the ±1ns "UniformTable" note in
// MessagePackSerializer.cs. The FormatterTypeId table read replaced the GVM (the thing
// worth 2ns in the pre-redesign codebase), so today's uniform path already banks that
// win. The 7.88ns memory was the lucky tail of per-process layout variance (identical
// code measured 7.9-14.2ns across the Jul 17 logs).
public class GenVsHandAsArrayBenchmark
{
    System.Buffers.ArrayBufferWriter<byte> buffer = new(); // same reused writer as NerdbankOfficialBenchmark
    UltraMessagePack.MessagePackSerializer handwritten = default!;

    [GlobalSetup]
    public void Setup()
    {
        handwritten = new UltraMessagePack.MessagePackSerializer(
            new HandAsArrayFormatterFactory(),
            UltraMessagePack.PrimitiveFormatterFactory.Instance,
            UltraMessagePack.GenericFormatterFactory.Instance);

        var oracle = MessagePack.MessagePackSerializer.Serialize(NbData.PocoAsArraySingle, MessagePack.MessagePackSerializerOptions.Standard);
        if (!UltraMessagePack.MessagePackSerializer.Default.Serialize(NbData.PocoAsArraySingle).AsSpan().SequenceEqual(oracle)) throw new InvalidOperationException("generated bytes != oracle");
        if (!handwritten.Serialize(NbData.PocoAsArraySingle).AsSpan().SequenceEqual(oracle)) throw new InvalidOperationException("handwritten bytes != oracle");
    }

    [Benchmark(Baseline = true)]
    public void SerializeGenerated()
    {
        UltraMessagePack.MessagePackSerializer.Default.Serialize(buffer, NbData.PocoAsArraySingle);
        buffer.Clear();
    }

    [Benchmark]
    public void SerializeHandwritten()
    {
        handwritten.Serialize(buffer, NbData.PocoAsArraySingle);
        buffer.Clear();
    }

    // replica of the DELETED static-entry design (screenshot ②): a static readonly
    // frozen cache holding the formatter for the exact (BufferWriterWriteBuffer,
    // ReadOnlySpanReadBuffer, T) instantiation, read directly — no per-call
    // resolver.GetFormatter (FormatterTypeId static + table index + Unsafe.As). Measures
    // what deleting DefaultCache in the UniformTable redesign cost on THIS entry.
    static class FrozenCache
    {
        public static readonly UltraMessagePack.IMessagePackFormatter<BufferWriterWriteBuffer, ReadOnlySpanReadBuffer, NbPocoAsArray> Formatter =
            UltraMessagePack.MessagePackSerializer.Default.Resolver.GetFormatter<BufferWriterWriteBuffer, ReadOnlySpanReadBuffer, NbPocoAsArray>();
    }

    [Benchmark]
    public void SerializeStaticCached()
    {
        var buf = new BufferWriterWriteBuffer(buffer);
        try
        {
            var state = new UltraMessagePack.SerializeState();
            var value = NbData.PocoAsArraySingle;
            FrozenCache.Formatter.Serialize(ref buf, ref state, ref value);
            buf.Flush();
        }
        finally
        {
            buf.Dispose();
        }
        buffer.Clear();
    }
}

// verbatim copy of the deleted hand-written formatter (git HEAD~ NerdbankOfficialBenchmark.cs)
public sealed class HandAsArrayFormatter<TWriteBuffer, TReadBuffer> : UltraMessagePack.IMessagePackFormatter<TWriteBuffer, TReadBuffer, NbPocoAsArray>
    where TWriteBuffer : struct, IWriteBuffer, allows ref struct
    where TReadBuffer : struct, IReadBuffer, allows ref struct
{
    public void Initialize(UltraMessagePack.MessagePackFormatterResolver resolver)
    {
    }

    public void Serialize(ref TWriteBuffer buffer, ref UltraMessagePack.SerializeState state, ref NbPocoAsArray value)
    {
        ref var destination = ref buffer.GetReference(1 + MaxInt32Length + GetMaxStringByteCount(value.SomeString));
        var offset = UnsafeWriteFixArrayHeader(ref destination, 2);
        offset += UnsafeWriteInt32(ref Unsafe.Add(ref destination, offset), value.SomeInt);
        offset += UnsafeWriteString(ref Unsafe.Add(ref destination, offset), value.SomeString);
        buffer.Advance(offset);
    }

    public void Deserialize(ref TReadBuffer buffer, ref UltraMessagePack.DeserializeState state, ref NbPocoAsArray value)
    {
        var count = buffer.ReadArrayHeader();
        if (value == null)
        {
            value = new NbPocoAsArray();
        }
        if (count > 0) value.SomeInt = buffer.ReadInt32();
        if (count > 1) value.SomeString = buffer.ReadString();
    }
}

public sealed class HandAsArrayFormatterFactory : UltraMessagePack.IMessagePackFormatterFactory
{
    public object? CreateFormatter<TWriteBuffer, TReadBuffer>(Type type)
        where TWriteBuffer : struct, IWriteBuffer, allows ref struct
        where TReadBuffer : struct, IReadBuffer, allows ref struct
    {
        return new HandAsArrayFormatter<TWriteBuffer, TReadBuffer>();
    }
}
