// <auto-generated />

#pragma warning disable 618, 612, 414, 168, CS1591, SA1129, SA1309, SA1312, SA1403, SA1649

#pragma warning disable CS8669 // We may leak nullable annotations into generated code.

using MsgPack = global::MessagePack;

namespace MessagePack {
internal partial class GeneratedMessagePackResolver {

	internal sealed class MyMessagePackObjectFormatter : MsgPack::Formatters.IMessagePackFormatter<global::MyMessagePackObject>
	{

		public void Serialize(ref MsgPack::MessagePackWriter writer, global::MyMessagePackObject value, MsgPack::MessagePackSerializerOptions options)
		{
			if (value == null)
			{
				writer.WriteNil();
				return;
			}

			writer.WriteArrayHeader(2);
			MsgPack::FormatterResolverExtensions.SerializeWithVerifyByValue<global::NS1.MyType>(ref writer, value.Value1, options);
			MsgPack::FormatterResolverExtensions.SerializeWithVerifyByValue<global::NS2.MyType>(ref writer, value.Value2, options);
		}

		public global::MyMessagePackObject Deserialize(ref MsgPack::MessagePackReader reader, MsgPack::MessagePackSerializerOptions options)
		{
			if (reader.TryReadNil())
			{
				return null;
			}

			options.Security.DepthStep(ref reader);
			var length = reader.ReadArrayHeader();
			var ____result = new global::MyMessagePackObject();

			for (int i = 0; i < length; i++)
			{
				switch (i)
				{
					case 0:
						____result.Value1 = MsgPack::FormatterResolverExtensions.DeserializeWithVerifyByValue<global::NS1.MyType>(ref reader, options);
						break;
					case 1:
						____result.Value2 = MsgPack::FormatterResolverExtensions.DeserializeWithVerifyByValue<global::NS2.MyType>(ref reader, options);
						break;
					default:
						reader.Skip();
						break;
				}
			}

			reader.Depth--;
			return ____result;
		}
	}
}
}
