parameters:
  includeMacOS:

steps:
- download: current
  artifact: coverageResults-Windows
  displayName: 🔻 Download Windows code coverage results
  continueOnError: true
- download: current
  artifact: coverageResults-Linux
  displayName: 🔻 Download Linux code coverage results
  continueOnError: true
- download: current
  artifact: coverageResults-macOS
  displayName: 🔻 Download macOS code coverage results
  continueOnError: true
  condition: and(succeeded(), ${{ parameters.includeMacOS }})
- powershell: azure-pipelines/Merge-CodeCoverage.ps1 -Path '$(Pipeline.Workspace)' -OutputFile coveragereport/merged.cobertura.xml -Format Cobertura -Verbose
  displayName: ⚙ Merge coverage
- task: PublishCodeCoverageResults@2
  displayName: 📢 Publish code coverage results to Azure DevOps
  inputs:
    summaryFileLocation: coveragereport/merged.cobertura.xml
    failIfCoverageEmpty: true
